import fs from "fs";
import path from "path";

const AI_BASE_URL = "http://localhost:20128/v1";
const AI_API_KEY = "sk-96f2316f84884524-2cee23-3c70805b";
const AI_CHAT_MODEL = "claude";

const BRAIN_PATH = path.resolve("c:/project/english-ai/data/curriculum_knowledge_brain.json");
const brain = JSON.parse(fs.readFileSync(BRAIN_PATH, "utf-8"));

export interface ModuleSyllabusPlan {
  id: string;
  levelId: string;
  cefr: string;
  orderIndex: number;
  title: string;
  group: string;
  objective: string;
  complexity: "basic" | "medium" | "deep";
  isExam: boolean;
}

// Sublevels for B1 & B2
export const B1_B2_PLANS: ModuleSyllabusPlan[] = [
  // ================= B1.4 (Workplace Communication & Service Engagements) =================
  {
    id: "B1.4-M01",
    levelId: "B1.4",
    cefr: "B1",
    orderIndex: 40,
    title: "Unit 1: Professional Emailing & Tactful Requests",
    group: "Workplace Communication",
    objective: "Mampu menyusun email profesional dengan modal politeness (could, would, may) dan formula kesopanan standar bisnis.",
    complexity: "medium",
    isExam: false,
  },
  {
    id: "B1.4-M02",
    levelId: "B1.4",
    cefr: "B1",
    orderIndex: 41,
    title: "Unit 2: Client Meetings: Agreeing, Disagreeing & Diplomatic Hedging",
    group: "Professional Interaction",
    objective: "Mampu menyampaikan persetujuan dan sanggahan secara santun dalam rapat kerja menggunakan phrasing diplomatis.",
    complexity: "medium",
    isExam: false,
  },
  {
    id: "B1.4-M03",
    levelId: "B1.4",
    cefr: "B1",
    orderIndex: 42,
    title: "Unit 3: Customer Service & De-escalating Client Complaints",
    group: "Service Excellence",
    objective: "Mampu menangani komplain pelanggan menggunakan bahasa empati, kalimat pasif sopan, dan solusi solutif.",
    complexity: "medium",
    isExam: false,
  },
  {
    id: "B1.4-M04",
    levelId: "B1.4",
    cefr: "B1",
    orderIndex: 43,
    title: "Unit 4: Describing Workplace Trends & Numerical Data",
    group: "Data & Reports",
    objective: "Mampu menjelaskan grafik tren bisnis sederhana (increase steadily, drop sharply) dengan preposisi angka yang akurat.",
    complexity: "medium",
    isExam: false,
  },
  {
    id: "B1.4-M05",
    levelId: "B1.4",
    cefr: "B1",
    orderIndex: 44,
    title: "Unit 5: Business Travel, Hotel Bookings & Airport Logistics",
    group: "Travel & Hospitality",
    objective: "Mampu melakukan koordinasi perjalanan dinas, check-in, dan penanganan keterlambatan transportasi secara percaya diri.",
    complexity: "medium",
    isExam: false,
  },
  {
    id: "B1.4-M06",
    levelId: "B1.4",
    cefr: "B1",
    orderIndex: 45,
    title: "Unit 6: Job Descriptions & Delegating Team Responsibilities",
    group: "Management & Workflow",
    objective: "Mampu mendeskripsikan rincian pekerjaan dan mendelegasikan tugas menggunakan causative verbs (have/make/get).",
    complexity: "medium",
    isExam: false,
  },
  {
    id: "B1.4-M07",
    levelId: "B1.4",
    cefr: "B1",
    orderIndex: 46,
    title: "Unit 7: Product Demos & Persuasive Value Propositions",
    group: "Marketing & Sales",
    objective: "Mampu mendemonstrasikan keunggulan produk dengan comparative/superlative modifier (far better, slightly faster).",
    complexity: "medium",
    isExam: false,
  },
  {
    id: "B1.4-M08",
    levelId: "B1.4",
    cefr: "B1",
    orderIndex: 47,
    title: "Unit 8: Office Health, Safety & Ergonomic Regulations",
    group: "Health & Workplace Norms",
    objective: "Mampu memahami dan menyusun panduan keselamatan kerja menggunakan modal obligation (must, have to, should).",
    complexity: "medium",
    isExam: false,
  },
  {
    id: "B1.4-M09",
    levelId: "B1.4",
    cefr: "B1",
    orderIndex: 48,
    title: "Unit 9: Networking Events & Breaking the Ice with Colleagues",
    group: "Networking & Small Talk",
    objective: "Mampu membuka percakapan networking profesional dengan tag questions dan topik netral yang cair.",
    complexity: "medium",
    isExam: false,
  },
  {
    id: "B1.4-M10",
    levelId: "B1.4",
    cefr: "B1",
    orderIndex: 49,
    title: "Unit 10: Telephone Etiquette, Messages & Follow-Up Calls",
    group: "Telecommunication",
    objective: "Mampu melakukan panggilan telepon bisnis, mencatat pesan penting, dan mengonfirmasi janji temu tanpa keraguan.",
    complexity: "medium",
    isExam: false,
  },
  {
    id: "B1.4-M11",
    levelId: "B1.4",
    cefr: "B1",
    orderIndex: 50,
    title: "Unit 11: Budgeting & Negotiating Basic Supplier Discounts",
    group: "Finance & Negotiation",
    objective: "Mampu mendiskusikan anggaran biaya dan menegosiasikan penawaran harga menggunakan conditional tipe 1 & 2.",
    complexity: "medium",
    isExam: false,
  },
  {
    id: "B1.4-M12",
    levelId: "B1.4",
    cefr: "B1",
    orderIndex: 51,
    title: "Unit 12: Project Retrospectives & Sharing Constructive Feedback",
    group: "Team Performance",
    objective: "Mampu mengevaluasi keberhasilan proyek dan memberikan umpan balik konstruktif dengan phrasing diplomatis.",
    complexity: "medium",
    isExam: false,
  },
  {
    id: "B1.4-M13",
    levelId: "B1.4",
    cefr: "B1",
    orderIndex: 52,
    title: "Ujian Kelulusan B1.4: Evaluasi Komprehensif Applied Workplace English",
    group: "Graduation Assessment",
    objective: "Menguji penguasaan komunikasi profesional, penanganan komplain, negosiasi dasar, dan tata bahasa kerja B1.4.",
    complexity: "deep",
    isExam: true,
  },

  // ================= B1.5 (Social Debates & Pre-B2 Fluency) =================
  {
    id: "B1.5-M01",
    levelId: "B1.5",
    cefr: "B1",
    orderIndex: 53,
    title: "Unit 1: The Influence of Social Media on Modern Youth",
    group: "Media & Society",
    objective: "Mampu mengemukakan argumen pro dan kontra terkait pengaruh media sosial dengan connective phrases yang terstruktur.",
    complexity: "medium",
    isExam: false,
  },
  {
    id: "B1.5-M02",
    levelId: "B1.5",
    cefr: "B1",
    orderIndex: 54,
    title: "Unit 2: Environmental Choices: Plastic Pollution & Renewable Habit",
    group: "Ecology & Sustainability",
    objective: "Mampu mendiskusikan krisis lingkungan dan solusi ramah lingkungan menggunakan passive voice dan cause-effect clauses.",
    complexity: "medium",
    isExam: false,
  },
  {
    id: "B1.5-M03",
    levelId: "B1.5",
    cefr: "B1",
    orderIndex: 55,
    title: "Unit 3: Cultural Traditions vs. Modern Lifestyles",
    group: "Culture & Anthropology",
    objective: "Mampu membandingkan tradisi lokal dan gaya hidup urban kontemporer menggunakan past habits (used to vs. would).",
    complexity: "medium",
    isExam: false,
  },
  {
    id: "B1.5-M04",
    levelId: "B1.5",
    cefr: "B1",
    orderIndex: 56,
    title: "Unit 4: Artificial Intelligence & Future Careers",
    group: "Technology & Future",
    objective: "Mampu berspekulasi mengenai masa depan lapangan kerja di era AI menggunakan future perfect & future continuous.",
    complexity: "medium",
    isExam: false,
  },
  {
    id: "B1.5-M05",
    levelId: "B1.5",
    cefr: "B1",
    orderIndex: 57,
    title: "Unit 5: Consumerism, Fast Fashion & Conscious Shopping",
    group: "Economics & Lifestyle",
    objective: "Mampu mengkritisi tren belanja impulsif dan dampak industri fashion dengan modal deduction (must be, can't be).",
    complexity: "medium",
    isExam: false,
  },
  {
    id: "B1.5-M06",
    levelId: "B1.5",
    cefr: "B1",
    orderIndex: 58,
    title: "Unit 6: Mental Health, Work-Life Balance & Wellbeing",
    group: "Health & Psychology",
    objective: "Mampu mendiskusikan manajemen stres dan keseimbangan hidup dengan phrasal verbs seputar kesehatan mental.",
    complexity: "medium",
    isExam: false,
  },
  {
    id: "B1.5-M07",
    levelId: "B1.5",
    cefr: "B1",
    orderIndex: 59,
    title: "Unit 7: Remote Working vs. Office Life: The Future of Work",
    group: "Work Dynamics",
    objective: "Mampu menyusun opini berimbang tentang model kerja remote versus kantor menggunakan concession clauses (although, even though).",
    complexity: "medium",
    isExam: false,
  },
  {
    id: "B1.5-M08",
    levelId: "B1.5",
    cefr: "B1",
    orderIndex: 60,
    title: "Unit 8: Urban Mobility: Public Transport vs. Electric Vehicles",
    group: "Transportation & Cities",
    objective: "Mampu mendebat kebijakan tata kota dan transportasi berkelanjutan dengan conditional sentences yang lebih kompleks.",
    complexity: "medium",
    isExam: false,
  },
  {
    id: "B1.5-M09",
    levelId: "B1.5",
    cefr: "B1",
    orderIndex: 61,
    title: "Unit 9: Cinema, Storytelling & The Psychology of Fear",
    group: "Arts & Entertainment",
    objective: "Mampu mengulas film atau cerita naratif menggunakan participle clauses dan kosakata emosional tingkat menengah.",
    complexity: "medium",
    isExam: false,
  },
  {
    id: "B1.5-M10",
    levelId: "B1.5",
    cefr: "B1",
    orderIndex: 62,
    title: "Unit 10: Digital Privacy, Cybersecurity & Personal Data",
    group: "Cyber Society",
    objective: "Mampu membahas isu keamanan data dan hak privasi digital dengan tata bahasa passive reporting (is said to be, is believed that).",
    complexity: "medium",
    isExam: false,
  },
  {
    id: "B1.5-M11",
    levelId: "B1.5",
    cefr: "B1",
    orderIndex: 63,
    title: "Unit 11: Food Waste & Global Food Security",
    group: "Global Issues",
    objective: "Mampu menganalisis masalah pemborosan pangan dan solusi ketahanan pangan global dengan quantifier dan adverb of degree.",
    complexity: "medium",
    isExam: false,
  },
  {
    id: "B1.5-M12",
    levelId: "B1.5",
    cefr: "B1",
    orderIndex: 64,
    title: "Unit 12: Bridge to B2: Synthesizing Multiple Perspectives into Clear Arguments",
    group: "Capstone Synthesis",
    objective: "Mampu memadukan berbagai sudut pandang opini menjadi argumen kohesif yang siap melangkah ke tingkat B2 Vantage.",
    complexity: "medium",
    isExam: false,
  },
  {
    id: "B1.5-M13",
    levelId: "B1.5",
    cefr: "B1",
    orderIndex: 65,
    title: "Ujian Kelulusan B1.5: Evaluasi Komprehensif Pre-B2 Fluency & Social Debates",
    group: "Graduation Assessment",
    objective: "Menguji kemampuan siswa dalam berdebat, sintesis opini sosial, dan penguasaan tata bahasa pra-B2 secara komprehensif.",
    complexity: "deep",
    isExam: true,
  },

  // ================= B2.4 (Academic Argumentation & Synthesis) =================
  {
    id: "B2.4-M01",
    levelId: "B2.4",
    cefr: "B2",
    orderIndex: 40,
    title: "Unit 1: Structuring Academic Theses & Topic Sentences",
    group: "Academic Writing & Rhetoric",
    objective: "Mampu menyusun tesis akademik yang tajam dan kalimat topik paragraf dengan nominalisasi dan kohesi formal.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "B2.4-M02",
    levelId: "B2.4",
    cefr: "B2",
    orderIndex: 41,
    title: "Unit 2: Cause, Effect & Counter-Argumentative Structures",
    group: "Logical Reasoning",
    objective: "Mampu menyajikan hubungan sebab-akibat multi-faktor dan menyanggah counter-arguments dengan linking adverbs tingkat lanjut.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "B2.4-M03",
    levelId: "B2.4",
    cefr: "B2",
    orderIndex: 42,
    title: "Unit 3: Interpreting Academic Research Data & Charts",
    group: "Research & Statistics",
    objective: "Mampu menganalisis data survei, grafik batang, dan tren demografis dengan bahasa deskriptif akademis presisi.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "B2.4-M04",
    levelId: "B2.4",
    cefr: "B2",
    orderIndex: 43,
    title: "Unit 4: Inverted Conditionals & Formal Supposition (Had I known, Were we to)",
    group: "Advanced Grammar",
    objective: "Mampu menerapkan conditional inversi formal dalam wacana akademik dan korespondensi resmi tingkat tinggi.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "B2.4-M05",
    levelId: "B2.4",
    cefr: "B2",
    orderIndex: 44,
    title: "Unit 5: Ethical Dilemmas in Scientific Innovation & Bioengineering",
    group: "Ethics & Science",
    objective: "Mampu memperdebatkan dilema etis rekayasa genetika dan bioteknologi dengan hedging verbs (appears to, indicates that).",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "B2.4-M06",
    levelId: "B2.4",
    cefr: "B2",
    orderIndex: 45,
    title: "Unit 6: Global Macroeconomics, Inflation & Monetary Policies",
    group: "Economics & Policy",
    objective: "Mampu mendiskusikan mekanisme inflasi, suku bunga, dan kebijakan fiskal dengan kolokasi ekonomi tingkat atas.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "B2.4-M07",
    levelId: "B2.4",
    cefr: "B2",
    orderIndex: 46,
    title: "Unit 7: Defending Arguments in Academic Seminars & Viva Voce",
    group: "Academic Speaking",
    objective: "Mampu mempertahankan argumen dan menjawab pertanyaan kritis audiens dalam presentasi seminar akademis.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "B2.4-M08",
    levelId: "B2.4",
    cefr: "B2",
    orderIndex: 47,
    title: "Unit 8: Complex Passive Structures & Impersonal Reporting in Journalistic Prose",
    group: "Stylistic Grammar",
    objective: "Mampu menguasai impersonal passive reporting (It is broadly asserted that, The phenomenon is believed to stem from).",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "B2.4-M09",
    levelId: "B2.4",
    cefr: "B2",
    orderIndex: 48,
    title: "Unit 9: Sociology of Urbanisation & Demographic Shifts",
    group: "Sociology & Demographics",
    objective: "Mampu menganalisis dampak migrasi desa-kota dan penuaan populasi dengan klausa adverbial komparatif mendalam.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "B2.4-M10",
    levelId: "B2.4",
    cefr: "B2",
    orderIndex: 49,
    title: "Unit 10: Environmental Jurisprudence & Climate Legislation",
    group: "Law & Environment",
    objective: "Mampu membahas traktat iklim internasional dan kepatuhan hukum lingkungan menggunakan register hukum formal.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "B2.4-M11",
    levelId: "B2.4",
    cefr: "B2",
    orderIndex: 50,
    title: "Unit 11: Critical Evaluation of Sources & Avoiding Plagiarism",
    group: "Scholarly Integrity",
    objective: "Mampu melakukan paraphrase canggih, sintesis multi-sumber, dan atribusi referensi tanpa kehilangan makna asli.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "B2.4-M12",
    levelId: "B2.4",
    cefr: "B2",
    orderIndex: 51,
    title: "Unit 12: Executive Summaries & Policy Brief Formulation",
    group: "Executive Writing",
    objective: "Mampu menyusun ringkasan eksekutif dan rekomendasi kebijakan publik dengan kepadatan leksikal yang ringkas dan padat.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "B2.4-M13",
    levelId: "B2.4",
    cefr: "B2",
    orderIndex: 52,
    title: "Ujian Kelulusan B2.4: Evaluasi Komprehensif Academic Argumentation & Synthesis",
    group: "Graduation Assessment",
    objective: "Menguji pemahaman sintesis argumen akademis, inversi kondisional, impersonal reporting, dan penulisan formal B2.4.",
    complexity: "deep",
    isExam: true,
  },

  // ================= B2.5 (Nuanced Persuasion & Bridge to C1) =================
  {
    id: "B2.5-M01",
    levelId: "B2.5",
    cefr: "B2",
    orderIndex: 53,
    title: "Unit 1: The Rhetoric of Persuasion: Ethos, Pathos & Logos",
    group: "Rhetoric & Oratory",
    objective: "Mampu menyusun pidato persuasif yang memadukan kredibilitas, emosi, dan logika dengan perangkat retoris klasik.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "B2.5-M02",
    levelId: "B2.5",
    cefr: "B2",
    orderIndex: 54,
    title: "Unit 2: Mixed Conditionals in Real-World Regret & Consequence",
    group: "Advanced Grammar",
    objective: "Mampu menguasai mixed conditionals (past condition with present result, and vice-versa) secara fasih dan alami.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "B2.5-M03",
    levelId: "B2.5",
    cefr: "B2",
    orderIndex: 55,
    title: "Unit 3: Cross-Cultural Negotiation & Strategic Compromise",
    group: "International Diplomacy",
    objective: "Mampu menavigasi perbedaan budaya dalam negosiasi bisnis internasional dengan taktik konsesi yang halus.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "B2.5-M04",
    levelId: "B2.5",
    cefr: "B2",
    orderIndex: 44,
    title: "Unit 4: Advanced Subjunctive & Formulaic Legal Expressions",
    group: "Formal Registers",
    objective: "Mampu menggunakan present subjunctive (mandate that he be, demand that she submit) dalam konteks formal.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "B2.5-M05",
    levelId: "B2.5",
    cefr: "B2",
    orderIndex: 57,
    title: "Unit 5: Behavioral Economics & Cognitive Biases in Consumer Choice",
    group: "Psychology & Markets",
    objective: "Mampu menganalisis bias kognitif (anchoring, loss aversion) dalam keputusan ekonomi menggunakan frasa akademis nuansatif.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "B2.5-M06",
    levelId: "B2.5",
    cefr: "B2",
    orderIndex: 58,
    title: "Unit 6: Cleft Sentences for Dramatic Emphasis (It is... that, What we need is...)",
    group: "Syntactic Emphasis",
    objective: "Mampu menggunakan it-cleft dan wh-cleft untuk memberikan penekanan tajam pada poin utama argumen lisan maupun tulisan.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "B2.5-M07",
    levelId: "B2.5",
    cefr: "B2",
    orderIndex: 59,
    title: "Unit 7: Geopolitical Alliances & Global Security Frameworks",
    group: "Geopolitics",
    objective: "Mampu mendiskusikan dinamika pakta keamanan regional dan diplomasi multilateral dengan kosakata geopolitik presisi.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "B2.5-M08",
    levelId: "B2.5",
    cefr: "B2",
    orderIndex: 60,
    title: "Unit 8: Advanced Spoken Nuance: Sarcasm, Understatement & Irony",
    group: "Nuance & Pragmatics",
    objective: "Mampu mendeteksi dan menggunakan litotes (understatement), ironi bersahabat, dan modulasi intonasi penutur asli.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "B2.5-M09",
    levelId: "B2.5",
    cefr: "B2",
    orderIndex: 61,
    title: "Unit 9: Editorial Analysis & Deconstructing Media Bias",
    group: "Media Analysis",
    objective: "Mampu membedah sudut pandang redaksional surat kabar ternama dan mengenali framing berita dengan kritis.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "B2.5-M10",
    levelId: "B2.5",
    cefr: "B2",
    orderIndex: 62,
    title: "Unit 10: Environmental Degrowth vs. Sustainable Green Innovation",
    group: "Sustainable Futures",
    objective: "Mampu menguji perdebatan antara paradigma degrowth versus inovasi pasar hijau dengan wacana dialektis berbobot.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "B2.5-M11",
    levelId: "B2.5",
    cefr: "B2",
    orderIndex: 63,
    title: "Unit 11: Corporate Governance, Ethics & Whistleblowing Policies",
    group: "Business Ethics",
    objective: "Mampu membahas skandal korporat dan kewajiban moral pelapor pelanggaran dengan register profesional etis.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "B2.5-M12",
    levelId: "B2.5",
    cefr: "B2",
    orderIndex: 64,
    title: "Unit 12: Bridge to C1: Autonomous Academic Debate & Complex Dialectics",
    group: "Capstone Synthesis",
    objective: "Mampu menyintesis seluruh keterampilan B2 menjadi kefasihan mandiri yang siap menembus standar C1 Operational Proficiency.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "B2.5-M13",
    levelId: "B2.5",
    cefr: "B2",
    orderIndex: 65,
    title: "Ujian Kelulusan B2.5: Evaluasi Komprehensif Nuanced Persuasion & Bridge to C1",
    group: "Graduation Assessment",
    objective: "Evaluasi akhir level B2: menguji penguasaan mixed conditionals, cleft sentences, retorika persuasif, dan register formal.",
    complexity: "deep",
    isExam: true,
  },
];
