export interface ModuleSyllabusPlan {
  id: string;
  levelId: string;
  cefr: string;
  orderIndex: number;
  title: string;
  group: string;
  objective: string;
  complexity: "basic" | "medium" | "deep";
  isExam: boolean;
}

export const C1_EXPANDED_PLANS: ModuleSyllabusPlan[] = [
  // ================= C1.4 (Complex Inversion, Concession & Rhetoric) =================
  {
    id: "C1.4-M01",
    levelId: "C1.4",
    cefr: "C1",
    orderIndex: 40,
    title: "Unit 1: Negative and Limiting Inversion in High Oratory (Under no circumstances, Seldom)",
    group: "Syntactic Mastery",
    objective: "Mampu menggunakan inversi negatif dan pembatas untuk menciptakan resonansi retoris berwibawa dalam pidato dan tulisan formal.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "C1.4-M02",
    levelId: "C1.4",
    cefr: "C1",
    orderIndex: 41,
    title: "Unit 2: Tactical Concession Clauses (Albeit, Notwithstanding, Inasmuch as)",
    group: "Advanced Syntax",
    objective: "Mampu menyusun konsesi taktikal dengan konjungsi subordinatif tingkat tinggi tanpa melemahkan premis utama argumen.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "C1.4-M03",
    levelId: "C1.4",
    cefr: "C1",
    orderIndex: 42,
    title: "Unit 3: Rhetorical Fronting, Topicalisation & Information Packaging",
    group: "Discourse Grammar",
    objective: "Mampu memanipulasi urutan klausa melalui fronting untuk mengendalikan fokus perhatian pendengar secara presisi.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "C1.4-M04",
    levelId: "C1.4",
    cefr: "C1",
    orderIndex: 43,
    title: "Unit 4: Nominalisation and Lexical Density in Scholarly Treatises",
    group: "Academic Prose",
    objective: "Mampu mengubah konstruksi verbal menjadi frasa nomina padat untuk meningkatkan bobot akademis tulisan riset.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "C1.4-M05",
    levelId: "C1.4",
    cefr: "C1",
    orderIndex: 44,
    title: "Unit 5: Chiasmus, Antithesis & Parallelism in Persuasive Speeches",
    group: "Classical Rhetoric",
    objective: "Mampu menyisipkan perangkat retoris klasik (antitesis dan kiasmus) untuk memperkuat daya gugah narasi kepemimpinan.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "C1.4-M06",
    levelId: "C1.4",
    cefr: "C1",
    orderIndex: 45,
    title: "Unit 6: Attitude Adverbials & Epistemic Stance Staging",
    group: "Pragmatic Stance",
    objective: "Mampu memodulasi kepastian wacana menggunakan attitude adverbials (Incontestably, Presumptively, Manifestly).",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "C1.4-M07",
    levelId: "C1.4",
    cefr: "C1",
    orderIndex: 46,
    title: "Unit 7: Elaborate Passive Causatives & Institutional Accountability",
    group: "Institutional Grammar",
    objective: "Mampu menyusun wacana pertanggungjawaban kebijakan publik menggunakan bentuk pasif kausatif canggih.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "C1.4-M08",
    levelId: "C1.4",
    cefr: "C1",
    orderIndex: 47,
    title: "Unit 8: Metaphoric Idioms in Macroeconomic Forecasting",
    group: "Applied Collocations",
    objective: "Mampu mendiskusikan siklus pasar global menggunakan metafora ekonomi penutur asli (soft landing, black swan, headwinds).",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "C1.4-M09",
    levelId: "C1.4",
    cefr: "C1",
    orderIndex: 48,
    title: "Unit 9: Subjunctive Mood in Sovereign Declarations & Statutory Texts",
    group: "Statutory English",
    objective: "Mampu menguasai pemakaian subjunctive formal dalam draf perjanjian dan resolusi kelembagaan resmi.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "C1.4-M10",
    levelId: "C1.4",
    cefr: "C1",
    orderIndex: 49,
    title: "Unit 10: Extended Participle Constructions & Cohesive Flow",
    group: "Cohesive Synthesis",
    objective: "Mampu menyusun rantai klausa partisipial yang kohesif tanpa menimbulkan dangling modifiers.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "C1.4-M11",
    levelId: "C1.4",
    cefr: "C1",
    orderIndex: 50,
    title: "Unit 11: Deconstructing Satire & Editorial Subtext in Broadsheets",
    group: "Media Deconstruction",
    objective: "Mampu mengurai lapisan ironi halus, sarkasme tersirat, dan bias sudut pandang pada tajuk rencana media internasional.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "C1.4-M12",
    levelId: "C1.4",
    cefr: "C1",
    orderIndex: 51,
    title: "Unit 12: Capstone Synthesis: The Sovereign Academic Monologue",
    group: "Academic Monologue",
    objective: "Mampu menyampaikan monolog ilmiah 5 menit dengan struktur tesis berimbang, transisi elegan, dan diksi C1 presisi.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "C1.4-M13",
    levelId: "C1.4",
    cefr: "C1",
    orderIndex: 52,
    title: "Ujian Kelulusan C1.4: Evaluasi Komprehensif Complex Inversion & Advanced Rhetoric",
    group: "Graduation Assessment",
    objective: "Menguji penguasaan inversi, konsesi taktikal, retorika pidato, dan sintaksis tingkat tinggi C1.4.",
    complexity: "deep",
    isExam: true,
  },

  // ================= C1.5 (Academic Peer Review & Empirical Critiques) =================
  {
    id: "C1.5-M01",
    levelId: "C1.5",
    cefr: "C1",
    orderIndex: 53,
    title: "Unit 1: The Art of Academic Hedging & Nuanced Epistemic Humility",
    group: "Scholarly Tone",
    objective: "Mampu membatasi klaim temuan empiris secara elegan menggunakan hedging verbs (purports to, lends credence to).",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "C1.5-M02",
    levelId: "C1.5",
    cefr: "C1",
    orderIndex: 54,
    title: "Unit 2: Writing Devastatingly Polite Peer Review Critiques",
    group: "Academic Dialogue",
    objective: "Mampu menulis telaah kritis atas manuskrip ilmiah kolega dengan bahasa kolegial yang konstruktif namun tajam.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "C1.5-M03",
    levelId: "C1.5",
    cefr: "C1",
    orderIndex: 55,
    title: "Unit 3: Methodological Scrutiny: Questioning Quantitative Validity",
    group: "Methodological Debate",
    objective: "Mampu mendebat keabsahan metodologi kuantitatif, bias pengambilan sampel, dan batas inferensi statistik.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "C1.5-M04",
    levelId: "C1.5",
    cefr: "C1",
    orderIndex: 56,
    title: "Unit 4: Qualitative Hermeneutics: Coding Nuanced Interview Transcripts",
    group: "Qualitative Discourse",
    objective: "Mampu mengartikulasikan temuan kualitatif etnografis dan analisis tematik dengan kosakata fenomenologis kaya.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "C1.5-M05",
    levelId: "C1.5",
    cefr: "C1",
    orderIndex: 57,
    title: "Unit 5: Synthesizing Contradictory Systematic Literature Reviews",
    group: "Meta-Synthesis",
    objective: "Mampu merekonsiliasi dua kubu literatur riset yang saling bertentangan menjadi sintesis teoretis baru yang koheren.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "C1.5-M06",
    levelId: "C1.5",
    cefr: "C1",
    orderIndex: 58,
    title: "Unit 6: Defending Theoretical Frameworks in Doctoral Colloquia",
    group: "Colloquium Defense",
    objective: "Mampu menjawab sanggahan teoretis dewan penguji dalam sidang doktoral dengan argumentasi berlapis.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "C1.5-M07",
    levelId: "C1.5",
    cefr: "C1",
    orderIndex: 59,
    title: "Unit 7: Ethical Dilemmas in Dual-Use Technologies & Biosafety",
    group: "Bioethics & Tech",
    objective: "Mampu menyusun telaah etis atas riset teknologi berisiko ganda dengan terminologi bioetika internasional.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "C1.5-M08",
    levelId: "C1.5",
    cefr: "C1",
    orderIndex: 60,
    title: "Unit 8: Grant Proposal Formulation & Justifying High-Risk Budgets",
    group: "Grant Writing",
    objective: "Mampu merumuskan proposal hibah riset berdaya pikat tinggi dengan argumen signifikansi dan ROI keilmuan.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "C1.5-M09",
    levelId: "C1.5",
    cefr: "C1",
    orderIndex: 61,
    title: "Unit 9: Interdisciplinary Jargon: Translating Hard Science for Policymakers",
    group: "Science Communication",
    objective: "Mampu mentransformasikan data sains kompleks menjadi rekomendasi kebijakan publik tanpa menyederhanakan substansi.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "C1.5-M10",
    levelId: "C1.5",
    cefr: "C1",
    orderIndex: 62,
    title: "Unit 10: Scholarly Refutation: Dismantling Flawed Statistical Arguments",
    group: "Scholarly Polemics",
    objective: "Mampu mematahkan klaim kausalitas semu (correlation vs causation) dengan rujukan logika formal penutur asli.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "C1.5-M11",
    levelId: "C1.5",
    cefr: "C1",
    orderIndex: 63,
    title: "Unit 11: The Epistemology of Artificial General Intelligence",
    group: "Philosophy of Science",
    objective: "Mampu memperdebatkan batas kognisi mesin, kesadaran sintetis, dan teori keselarasan nilai (alignment problem).",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "C1.5-M12",
    levelId: "C1.5",
    cefr: "C1",
    orderIndex: 64,
    title: "Unit 12: Drafting Policy Whitepapers with Unassailable Lexical Precision",
    group: "Whitepaper Synthesis",
    objective: "Mampu menyusun whitepaper kebijakan dengan kepadatan argumen solid dan alur rekomendasi implementatif.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "C1.5-M13",
    levelId: "C1.5",
    cefr: "C1",
    orderIndex: 65,
    title: "Ujian Kelulusan C1.5: Evaluasi Komprehensif Academic Peer Review & Research Synthesis",
    group: "Graduation Assessment",
    objective: "Menguji kemampuan sintesis telaah sejawat, ketepatan hedging, metodologi riset, dan argumentasi ilmiah C1.5.",
    complexity: "deep",
    isExam: true,
  },

  // ================= C1.6 (Diplomatic Negotiation & Executive Discourse) =================
  {
    id: "C1.6-M01",
    levelId: "C1.6",
    cefr: "C1",
    orderIndex: 66,
    title: "Unit 1: The Language of Diplomatic Ambiguity & Constructive Vagueness",
    group: "Diplomatic Registers",
    objective: "Mampu menggunakan ambiguitas diplomatik secara strategis untuk menjaga ruang kompromi dalam perundingan.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "C1.6-M02",
    levelId: "C1.6",
    cefr: "C1",
    orderIndex: 67,
    title: "Unit 2: Tactical Concessions & Tit-for-Tat Bargaining Strategies",
    group: "High-Stakes Negotiation",
    objective: "Mampu menukar konsesi bersyarat dalam negosiasi merger akuisisi atau traktat bilateral dengan phrasing elegan.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "C1.6-M03",
    levelId: "C1.6",
    cefr: "C1",
    orderIndex: 68,
    title: "Unit 3: Navigating Hostile Shareholder Interrogations",
    group: "Executive Governance",
    objective: "Mampu meredakan kepanikan pemegang saham dalam RUPS saat krisis pendapatan dengan ketenangan otoritatif.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "C1.6-M04",
    levelId: "C1.6",
    cefr: "C1",
    orderIndex: 69,
    title: "Unit 4: Formulating Sovereign Bilateral Treaties & MOUs",
    group: "Treaty Formulation",
    objective: "Mampu menyusun klausul traktat bilateral dengan terminologi hukum internasional yang mengikat dan presisi.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "C1.6-M05",
    levelId: "C1.6",
    cefr: "C1",
    orderIndex: 70,
    title: "Unit 5: Mediating Labor Disputes & Collective Bargaining Deadlocks",
    group: "Labor Diplomacy",
    objective: "Mampu memediasi kebuntuan perundingan serikat pekerja dengan teknik de-eskalasi emosi dan reframing objektif.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "C1.6-M06",
    levelId: "C1.6",
    cefr: "C1",
    orderIndex: 71,
    title: "Unit 6: Sovereign Debt Restructuring & Multilateral Finance",
    group: "Global Finance",
    objective: "Mampu bernegosiasi dalam kerangka restrukturisasi utang negara dengan lembaga moneter multilateral (IMF/World Bank).",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "C1.6-M07",
    levelId: "C1.6",
    cefr: "C1",
    orderIndex: 72,
    title: "Unit 7: Cross-Cultural Protocol & Managing Diplomatic Snubs",
    group: "Diplomatic Protocol",
    objective: "Mampu merespons pelanggaran protokol diplomatik internasional dengan martabat dan kehalusan berkelas.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "C1.6-M08",
    levelId: "C1.6",
    cefr: "C1",
    orderIndex: 73,
    title: "Unit 8: Executive Keynotes: Inspiring Global Organizational Alignment",
    group: "Executive Oratory",
    objective: "Mampu menyampaikan pidato utama CEO yang menginspirasi ribuan karyawan multinasional di tengah transformasi.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "C1.6-M09",
    levelId: "C1.6",
    cefr: "C1",
    orderIndex: 74,
    title: "Unit 9: Regulatory Compliance Audits & Inter-Jurisdictional Arbitration",
    group: "Arbitration",
    objective: "Mampu menyampaikan pembelaan korporat dalam forum arbitrase internasional di Jenewa atau Singapura.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "C1.6-M10",
    levelId: "C1.6",
    cefr: "C1",
    orderIndex: 75,
    title: "Unit 10: Whistleblower Depositions & Corporate Internal Enquiries",
    group: "Legal Interrogation",
    objective: "Mampu memimpin pemeriksaan saksi investigasi internal korporat dengan teknik interogasi yang sah dan netral.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "C1.6-M11",
    levelId: "C1.6",
    cefr: "C1",
    orderIndex: 76,
    title: "Unit 11: Drafting Non-Disclosure Agreements & Strategic Escapes",
    group: "Contractual Strategy",
    objective: "Mampu menganalisis celah klausul pengecualian dalam perjanjian kerahasiaan dan klausul force majeure.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "C1.6-M12",
    levelId: "C1.6",
    cefr: "C1",
    orderIndex: 77,
    title: "Unit 12: High-Level Consensual Communiqués & Summit Resolutions",
    group: "Summit Resolutions",
    objective: "Mampu merumuskan komunike bersama KTT antar-pemerintah yang menyelaraskan kepentingan multi-negara.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "C1.6-M13",
    levelId: "C1.6",
    cefr: "C1",
    orderIndex: 78,
    title: "Ujian Kelulusan C1.6: Evaluasi Komprehensif Diplomatic Negotiation & Executive Discourse",
    group: "Graduation Assessment",
    objective: "Menguji penguasaan bahasa diplomasi, negosiasi krisis eksekutif, arbitrase, dan perumusan komunike C1.6.",
    complexity: "deep",
    isExam: true,
  },

  // ================= C1.7 (High-Stakes Crisis Communication & Dialectical Synthesis) =================
  {
    id: "C1.7-M01",
    levelId: "C1.7",
    cefr: "C1",
    orderIndex: 79,
    title: "Unit 1: The Anatomy of a High-Stakes Public Apology & Crisis Press Briefing",
    group: "Crisis Communications",
    objective: "Mampu menyampaikan konferensi pers krisis publik yang tulus, bertanggung jawab, dan memitigasi litigasi hukum.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "C1.7-M02",
    levelId: "C1.7",
    cefr: "C1",
    orderIndex: 80,
    title: "Unit 2: Managing Hostile Investigative Broadcast Interviews",
    group: "Media Interrogation",
    objective: "Mampu menghadapi wawancara investigasi jurnalis agresif (BBC Hardtalk style) menggunakan teknik bridging berkelas.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "C1.7-M03",
    levelId: "C1.7",
    cefr: "C1",
    orderIndex: 81,
    title: "Unit 3: Dialectical Synthesis: Resolving Deep Existential Contradictions",
    group: "Dialectical Philosophy",
    objective: "Mampu membedah pertentangan paradoksikal (kebebasan vs keamanan) menjadi sintesis filsafat berbobot.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "C1.7-M04",
    levelId: "C1.7",
    cefr: "C1",
    orderIndex: 82,
    title: "Unit 4: Cyber Warfare Attribution & International Sovereign Condemnation",
    group: "Geopolitical Cyber",
    objective: "Mampu menyusun nota atribusi serangan siber kenegaraan di forum Dewan Keamanan PBB secara tegas dan terukur.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "C1.7-M05",
    levelId: "C1.7",
    cefr: "C1",
    orderIndex: 83,
    title: "Unit 5: Emergency Public Health Directives & Overcoming Skepticism",
    group: "Public Health Oratory",
    objective: "Mampu menyusun maklumat darurat kesehatan masyarakat yang menyeimbangkan otoritas medis dan empati publik.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "C1.7-M06",
    levelId: "C1.7",
    cefr: "C1",
    orderIndex: 84,
    title: "Unit 6: Humanitarian Corridor Negotiations in Armed Conflicts",
    group: "Humanitarian Law",
    objective: "Mampu memimpin perundingan gencatan senjata koridor kemanusiaan di bawah kerangka Konvensi Jenewa.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "C1.7-M07",
    levelId: "C1.7",
    cefr: "C1",
    orderIndex: 85,
    title: "Unit 7: De-escalating Mass Public Unrest & Civic Reconciliation",
    group: "Civic Peacebuilding",
    objective: "Mampu merancang orasi rekonsiliasi kebangsaan pasca-kerusuhan sipil untuk memulihkan kepercayaan publik.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "C1.7-M08",
    levelId: "C1.7",
    cefr: "C1",
    orderIndex: 86,
    title: "Unit 8: Climate Migration Treaties & Displaced Population Rights",
    group: "Ecology & Sovereignty",
    objective: "Mampu mengartikulasikan status suaka iklim dan perlindungan kedaulatan pulau tenggelam dengan terminologi C1 atas.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "C1.7-M09",
    levelId: "C1.7",
    cefr: "C1",
    orderIndex: 87,
    title: "Unit 9: Unraveling Sophistry & Logical Fallacies in Live Parliamentary Debates",
    group: "Parliamentary Debate",
    objective: "Mampu menelanjangi kesesatan logika lawan debat (ad hominem, false dilemma, strawman) dalam tempo seketika.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "C1.7-M10",
    levelId: "C1.7",
    cefr: "C1",
    orderIndex: 88,
    title: "Unit 10: Drafting Farewell Addresses & Enduring Institutional Legacies",
    group: "Statesmanship",
    objective: "Mampu menyusun pidato perpisahan negarawan yang meninggalkan pesan filosofis abadi bagi generasi mendatang.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "C1.7-M11",
    levelId: "C1.7",
    cefr: "C1",
    orderIndex: 89,
    title: "Unit 11: The Sovereign Epistemic Bridge: Crossing from C1 into C2 Mastery",
    group: "Capstone Transition",
    objective: "Mampu memadukan seluruh domain C1 menjadi penguasaan otonom yang siap memasuki level C2 Native Mastery.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "C1.7-M12",
    levelId: "C1.7",
    cefr: "C1",
    orderIndex: 90,
    title: "Unit 12: Dialectical Grand Defense: The 15-Minute Unrehearsed Colloquium",
    group: "Grand Defense",
    objective: "Mampu mempertahankan posisi filosofis spontan selama 15 menit menghadapi sanggahan panelis pakar penutur asli.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "C1.7-M13",
    levelId: "C1.7",
    cefr: "C1",
    orderIndex: 91,
    title: "Ujian Kelulusan C1.7: Evaluasi Komprehensif High-Stakes Crisis & Ultimate C1 Capstone",
    group: "Graduation Assessment",
    objective: "Ujian kelulusan akhir C1: evaluasi komprehensif retorika krisis, perundingan internasional, dan orasi dialektis.",
    complexity: "deep",
    isExam: true,
  },
];
