import { ModuleSyllabusPlan } from "./c1_expanded_plans";

export const C2_EXPANDED_PLANS: ModuleSyllabusPlan[] = [
  // ================= C2.4 (Forensic Linguistics & Syntactic Artistry) =================
  {
    id: "C2.4-M01",
    levelId: "C2.4",
    cefr: "C2",
    orderIndex: 40,
    title: "Unit 1: Forensic Linguistic Analysis: Resolving Contractual & Syntactic Ambiguities",
    group: "Forensic Linguistics",
    objective: "Mampu membedah ambiguitas sintaktis dan semantis dalam klausul hukum preseden tinggi dengan kecermatan forensik.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "C2.4-M02",
    levelId: "C2.4",
    cefr: "C2",
    orderIndex: 41,
    title: "Unit 2: Pragmatic Implicature & Gricean Maxims in Diplomatic Evasion",
    group: "Pragmatics & Implicature",
    objective: "Mampu mengeksploitasi dan mendekonstruksi pelanggaran maksim percakapan Grice untuk membaca niat tersembunyi antar-negara.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "C2.4-M03",
    levelId: "C2.4",
    cefr: "C2",
    orderIndex: 42,
    title: "Unit 3: Stylistic Register Modulation: From Colloquial Irony to Elizabethan Grandeur",
    group: "Register Mastery",
    objective: "Mampu berpindah secara instan dan alami antara slang kontemporer, prosa jurnalistik tinggi, hingga register arkaik.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "C2.4-M04",
    levelId: "C2.4",
    cefr: "C2",
    orderIndex: 43,
    title: "Unit 4: The Lexicography of Neologisms: Coinage, Etymology & Semantic Drift",
    group: "Lexicology",
    objective: "Mampu menganalisis pergeseran makna kata kontemporer dan menciptakan neologisme konseptual yang berdaya terima leksikal.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "C2.4-M05",
    levelId: "C2.4",
    cefr: "C2",
    orderIndex: 44,
    title: "Unit 5: Prosodic Nuance, Sarcastic Undertones & Micro-Intonation",
    group: "Prosody & Phonology",
    objective: "Mampu mengendalikan nada mikro, jeda dramatis, dan kontur intonasi untuk menyampaikan makna ganda tanpa cela.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "C2.4-M06",
    levelId: "C2.4",
    cefr: "C2",
    orderIndex: 45,
    title: "Unit 6: Deconstructing Forensic Cross-Examinations in Landmark Trials",
    group: "Judicial Oratory",
    objective: "Mampu menganalisis transkrip interogasi silang pengadilan bersejarah dan teknik jebakan saksi ahli penutur asli.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "C2.4-M07",
    levelId: "C2.4",
    cefr: "C2",
    orderIndex: 46,
    title: "Unit 7: Polysemy, Puns & High-Wit Verbal Jousting",
    group: "Verbal Artistry",
    objective: "Mampu membalas sindiran intelektual seketika menggunakan polisemi kata dan kelakar kata tingkat grandmaster.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "C2.4-M08",
    levelId: "C2.4",
    cefr: "C2",
    orderIndex: 47,
    title: "Unit 8: Syntactic Parallelism & Chiasmic Symmetry in Constitutional Texts",
    group: "Constitutional Prose",
    objective: "Mampu menyusun pembukaan konstitusi atau piagam luhur dengan keanggunan simetri sintaksis sekelas Magna Carta.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "C2.4-M09",
    levelId: "C2.4",
    cefr: "C2",
    orderIndex: 48,
    title: "Unit 9: Epistolary Rhetoric: The Art of the Devastating Formal Letter",
    group: "Epistolary Art",
    objective: "Mampu menulis surat resmi penolakan atau somasi yang begitu anggun dan berwibawa sehingga lawan tak berdaya menyanggah.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "C2.4-M10",
    levelId: "C2.4",
    cefr: "C2",
    orderIndex: 49,
    title: "Unit 10: Semiotic Disambiguation of Visual Propaganda & Media Frames",
    group: "Critical Semiotics",
    objective: "Mampu membedah metafora semiotika visual dan pembingkaian kognitif kampanye geopolitik global.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "C2.4-M11",
    levelId: "C2.4",
    cefr: "C2",
    orderIndex: 50,
    title: "Unit 11: The Mechanics of Dramatic Monologue & Theatrical Cadence",
    group: "Theatrical Cadence",
    objective: "Mampu menguasai ritme iambik, jeda cesura, dan resonansi vokal dalam monolog teatrikal puitis modern.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "C2.4-M12",
    levelId: "C2.4",
    cefr: "C2",
    orderIndex: 51,
    title: "Unit 12: Scholarly Synthesis: The Forensic Linguistic Dissertation Proposal",
    group: "Capstone Synthesis",
    objective: "Mampu menyusun proposal disertasi linguistik forensik yang mengurai paradoks semantis baru dalam wacana global.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "C2.4-M13",
    levelId: "C2.4",
    cefr: "C2",
    orderIndex: 52,
    title: "Ujian Kelulusan C2.4: Evaluasi Komprehensif Forensic Linguistics & Syntactic Artistry",
    group: "Graduation Assessment",
    objective: "Menguji penguasaan linguistik forensik, pragmatik implikatur, modulasi register, dan estetika sintaksis C2.4.",
    complexity: "deep",
    isExam: true,
  },

  // ================= C2.5 (Grandmaster Dialectics, Epigrammatic Wit & Satire) =================
  {
    id: "C2.5-M01",
    levelId: "C2.5",
    cefr: "C2",
    orderIndex: 53,
    title: "Unit 1: The Anatomy of Epigrammatic Wit: Crafting Unforgettable Aphorisms",
    group: "Aphoristic Rhetoric",
    objective: "Mampu merumuskan aforisme dan epigram padat makna setara Voltaire atau Oscar Wilde yang mengkristalkan kebenaran abadi.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "C2.5-M02",
    levelId: "C2.5",
    cefr: "C2",
    orderIndex: 54,
    title: "Unit 2: Juvenalian vs. Horatian Satire: Dissecting Institutional Absurdity",
    group: "Classical Satire",
    objective: "Mampu membedakan dan menggubah satire tajam (Juvenalian) serta satire lembut (Horatian) untuk mengkritik kepongahan birokrasi.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "C2.5-M03",
    levelId: "C2.5",
    cefr: "C2",
    orderIndex: 55,
    title: "Unit 3: Dialectical Irony & Reductio Ad Absurdum in High Philosophical Debate",
    group: "Dialectical Refutation",
    objective: "Mampu menggunakan reductio ad absurdum untuk meruntuhkan premis cacat lawan debat hingga batas ekstrem yang menggelikan.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "C2.5-M04",
    levelId: "C2.5",
    cefr: "C2",
    orderIndex: 56,
    title: "Unit 4: The Art of the Socratic Dialogue: Dismantling Dogma through Inquiry",
    group: "Socratic Method",
    objective: "Mampu memandu lawan bicara mengakui kontradiksi logikanya sendiri melalui untaian pertanyaan Sokrates yang bertingkat.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "C2.5-M05",
    levelId: "C2.5",
    cefr: "C2",
    orderIndex: 57,
    title: "Unit 5: Understatement (Litotes) as the Supreme Instrument of Power",
    group: "Litotes & Power",
    objective: "Mampu menggunakan litotes untuk menyampaikan penolakan telak atau penghinaan intelektual dengan keanggunan tertinggi.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "C2.5-M06",
    levelId: "C2.5",
    cefr: "C2",
    orderIndex: 58,
    title: "Unit 6: Oxford Union Parliamentary Sparring: Mastering Points of Information",
    group: "Parliamentary Oratory",
    objective: "Mampu mengajukan dan membalas interupsi (Point of Information) dalam debat parlementer Oxford dengan tangkas dan tajam.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "C2.5-M07",
    levelId: "C2.5",
    cefr: "C2",
    orderIndex: 59,
    title: "Unit 7: The Rhetoric of Cynicism, Stoicism & Nihilism in Literature",
    group: "Literary Philosophy",
    objective: "Mampu mendiskusikan dan menulis kritik sastra beraliran stoikisme dan eksistensialisme dengan diksi kanon sastra dunia.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "C2.5-M08",
    levelId: "C2.5",
    cefr: "C2",
    orderIndex: 60,
    title: "Unit 8: Lampooning Pseudoscience & Deconstructing Technocratic Techno-Babble",
    group: "Epistemic Polemic",
    objective: "Mampu menelanjangi istilah sok ilmiah (techno-babble) dan jargon korporat kosong dengan ketajaman logika jernih.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "C2.5-M09",
    levelId: "C2.5",
    cefr: "C2",
    orderIndex: 61,
    title: "Unit 9: Parody, Pastiche & Homage in Postmodern Creative Writing",
    group: "Creative Pastiche",
    objective: "Mampu meniru dan mereinterpretasi gaya bahasa penulis agung (Joyce, Woolf, Orwell) ke dalam pastiche kontemporer.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "C2.5-M10",
    levelId: "C2.5",
    cefr: "C2",
    orderIndex: 62,
    title: "Unit 10: The Sovereign Eulogy: Weaving Grief, Grandeur & Eternal Remembrance",
    group: "Monumental Eulogies",
    objective: "Mampu menggubah pidato pelepasan tokoh besar yang menyentuh relung sanubari sekaligus mengabadikan keteladanan abadi.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "C2.5-M11",
    levelId: "C2.5",
    cefr: "C2",
    orderIndex: 63,
    title: "Unit 11: The Epigrammatic Duel: Spontaneous Intellectual Banter",
    group: "Spontaneous Wit",
    objective: "Mampu terlibat dalam adu kelakar dan wit intelektual tanpa naskah menghadapi penutur asli paling fasih di dunia.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "C2.5-M12",
    levelId: "C2.5",
    cefr: "C2",
    orderIndex: 64,
    title: "Unit 12: Capstone Synthesis: The Dialectical Grand Invective",
    group: "Grand Invective",
    objective: "Mampu menyampaikan pidato polemik dialektis 10 menit yang secara meyakinkan mendekonstruksi paradigma ilmiah usang.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "C2.5-M13",
    levelId: "C2.5",
    cefr: "C2",
    orderIndex: 65,
    title: "Ujian Kelulusan C2.5: Evaluasi Komprehensif Grandmaster Dialectics & Epigrammatic Wit",
    group: "Graduation Assessment",
    objective: "Menguji penguasaan aforisme, satire, dialektika Sokrates, debat Oxford, dan retorika penutur asli tingkat maestro.",
    complexity: "deep",
    isExam: true,
  },

  // ================= C2.6 (Hermeneutic Analysis & Philosophical Treatises) =================
  {
    id: "C2.6-M01",
    levelId: "C2.6",
    cefr: "C2",
    orderIndex: 66,
    title: "Unit 1: Hermeneutic Close-Reading of Enlightenment Philosophers (Locke, Kant, Hume)",
    group: "Philosophical Hermeneutics",
    objective: "Mampu menelaah teks filsafat pencerahan asli dengan pemahaman mendalam atas nuansa leksikal abad ke-18.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "C2.6-M02",
    levelId: "C2.6",
    cefr: "C2",
    orderIndex: 67,
    title: "Unit 2: The Philosophy of Language: Wittgenstein, Russell & Semantic Atomism",
    group: "Analytic Philosophy",
    objective: "Mampu mendiskusikan batas bahasa dan realitas dunia melalui kerangka analitis Tractatus Logico-Philosophicus.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "C2.6-M03",
    levelId: "C2.6",
    cefr: "C2",
    orderIndex: 68,
    title: "Unit 3: Critiquing Historical Treatises on Geopolitics & Sovereign Realism (Hobbes, Machiavelli)",
    group: "Political Realism",
    objective: "Mampu membandingkan doktrin realisme politik klasik dengan tatanan multipolar abad ke-21 dalam register akademik agung.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "C2.6-M04",
    levelId: "C2.6",
    cefr: "C2",
    orderIndex: 69,
    title: "Unit 4: Epistemological Skepticism: Radical Doubt, Solipsism & Cognitive Bounds",
    group: "Epistemology",
    objective: "Mampu memperdebatkan hipotesis simulasi, keraguan radikal Descartes, dan batas kognitif kesadaran manusia.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "C2.6-M05",
    levelId: "C2.6",
    cefr: "C2",
    orderIndex: 70,
    title: "Unit 5: Moral Deontology vs. Radical Utilitarianism in Life-or-Death Bioethics",
    group: "Normative Ethics",
    objective: "Mampu mempertahankan posisi etis deontologis melawan utilitarianisme ekstrem dalam skenario alokasi sumber daya langka.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "C2.6-M06",
    levelId: "C2.6",
    cefr: "C2",
    orderIndex: 71,
    title: "Unit 6: Hermeneutics of Historic Supreme Court Majority Opinions",
    group: "Jurisprudence",
    objective: "Mampu menganalisis teks putusan Mahkamah Agung AS bersejarah (Brown v Board, Marbury v Madison) dengan diksi hukum konstitusi.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "C2.6-M07",
    levelId: "C2.6",
    cefr: "C2",
    orderIndex: 72,
    title: "Unit 7: Existentialism, Absurdism & The Meaning of Suffering (Camus, Kierkegaard, Frankl)",
    group: "Existential Philosophy",
    objective: "Mampu mengartikulasikan pencarian makna di tengah absurditas eksistensial dengan kekayaan leksikal fenomenologis mendalam.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "C2.6-M08",
    levelId: "C2.6",
    cefr: "C2",
    orderIndex: 73,
    title: "Unit 8: Post-Colonial Hermeneutics & The Subversion of Imperial Narratives",
    group: "Post-Colonial Theory",
    objective: "Mampu membedah wacana hegemoni bahasa dan mendekonstruksi teks kanonik melalui kacamata teori pascakolonial.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "C2.6-M09",
    levelId: "C2.6",
    cefr: "C2",
    orderIndex: 74,
    title: "Unit 9: Aesthetics, Sublimity & The Philosophy of Art (Burke, Kant, Schopenhauer)",
    group: "Aesthetic Theory",
    objective: "Mampu mendefinisikan pengalaman keluhuran rasa (the sublime) dan keindahan transendental dalam karya seni monumental.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "C2.6-M10",
    levelId: "C2.6",
    cefr: "C2",
    orderIndex: 75,
    title: "Unit 10: Hermeneutic Analysis of Sacred & Canonical Scriptures",
    group: "Comparative Textualism",
    objective: "Mampu menganalisis perbandingan metafora, arkaisme, dan resonansi spiritual dalam naskah suci terjemahan King James Bible.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "C2.6-M11",
    levelId: "C2.6",
    cefr: "C2",
    orderIndex: 76,
    title: "Unit 11: The Synthesis of Science and Metaphysics: Quantum Indeterminacy & Free Will",
    group: "Metaphysics & Physics",
    objective: "Mampu menyatukan wacana fisika kuantum dan perdebatan kehendak bebas manusia dalam esai filosofis yang brilian.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "C2.6-M12",
    levelId: "C2.6",
    cefr: "C2",
    orderIndex: 77,
    title: "Unit 12: Drafting the Definitive Philosophical Treatise on Human Consciousness",
    group: "Treatise Formulation",
    objective: "Mampu menulis traktat filosofis 3.000 kata dengan kohesi argumen tanpa cela, orisinalitas konseptual, dan gaya bahasa kanonik.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "C2.6-M13",
    levelId: "C2.6",
    cefr: "C2",
    orderIndex: 78,
    title: "Ujian Kelulusan C2.6: Evaluasi Komprehensif Hermeneutic Analysis & Philosophical Treatises",
    group: "Graduation Assessment",
    objective: "Menguji keahlian hermeneutika teks kanonik, filsafat analitik, etika normatif, yurisprudensi, dan penulisan traktat C2.6.",
    complexity: "deep",
    isExam: true,
  },

  // ================= C2.7 (The Sovereign English Speaker: Capstone Mastery) =================
  {
    id: "C2.7-M01",
    levelId: "C2.7",
    cefr: "C2",
    orderIndex: 79,
    title: "Unit 1: The Sovereign Speaker: Spontaneous Eloquence Under Hostile Scrutiny",
    group: "Sovereign Mastery",
    objective: "Mampu menunjukkan kefasihan penutur asli tanpa ragu dalam situasi tekanan tinggi dengan ketenangan aristokratik.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "C2.7-M02",
    levelId: "C2.7",
    cefr: "C2",
    orderIndex: 80,
    title: "Unit 2: The Architecture of Monumental Inaugural Addresses",
    group: "Presidential Oratory",
    objective: "Mampu menyusun dan menyampaikan pidato pelantikan kenegaraan yang menggerakkan nurani jutaan manusia lintas zaman.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "C2.7-M03",
    levelId: "C2.7",
    cefr: "C2",
    orderIndex: 81,
    title: "Unit 3: Effortless Idiomatic Mastery: Beyond the Native Speaker Horizon",
    group: "Idiomatic Sovereignty",
    objective: "Mampu menenun ribuan idiom terhalus, alusi sastra, dan metafora kultural ke dalam percakapan sehari-hari secara wajar.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "C2.7-M04",
    levelId: "C2.7",
    cefr: "C2",
    orderIndex: 82,
    title: "Unit 4: The Sovereign Diplomat: Brokering Peace Between Nuclear Powers",
    group: "Nuclear Diplomacy",
    objective: "Mampu memimpin perundingan penutupan krisis rudal antar-negara adidaya dengan presisi leksikal pembawa keselamatan dunia.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "C2.7-M05",
    levelId: "C2.7",
    cefr: "C2",
    orderIndex: 83,
    title: "Unit 5: The Nobel Lecture: Synthesizing a Lifetime of Intellectual Discovery",
    group: "Nobel Laureate Oratory",
    objective: "Mampu menyusun orasi ilmiah Nobel yang menyederhanakan penemuan monumental dengan kerendahan hati dan keagungan bahasa.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "C2.7-M06",
    levelId: "C2.7",
    cefr: "C2",
    orderIndex: 84,
    title: "Unit 6: Sovereign Satire: The Defiant Satirical Manifesto Against Tyranny",
    group: "Dissident Prose",
    objective: "Mampu menulis manifesto satir pembangkangan sipil yang menembus sensor tirani dengan kekuatan metafora yang tak terpatahkan.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "C2.7-M07",
    levelId: "C2.7",
    cefr: "C2",
    orderIndex: 85,
    title: "Unit 7: The Master of All Registers: The Chameleon Orator",
    group: "Total Modulation",
    objective: "Mampu menyesuaikan seluruh aspek bahasa seketika: berbicara akrab di jalanan, berdebat di senat, dan mengajar di akademi.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "C2.7-M08",
    levelId: "C2.7",
    cefr: "C2",
    orderIndex: 86,
    title: "Unit 8: Philosophical Dialectics on the Cosmic Destiny of Humanity",
    group: "Cosmic Philosophy",
    objective: "Mampu berwacana tentang masa depan miliaran tahun peradaban manusia dan kecerdasan super dengan keanggunan profetis.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "C2.7-M09",
    levelId: "C2.7",
    cefr: "C2",
    orderIndex: 87,
    title: "Unit 9: The Sovereign Cross-Examiner: The Masterclass in Unmasking Deception",
    group: "Ultimate Interrogation",
    objective: "Mampu mengurai lapisan kebohongan korporat dan geopolitik global melalui interogasi linguistik yang tak terbantahkan.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "C2.7-M10",
    levelId: "C2.7",
    cefr: "C2",
    orderIndex: 88,
    title: "Unit 10: The Universal Epilogue: Crafting Words That Echo for Centuries",
    group: "Universal Epilogue",
    objective: "Mampu menyusun kalimat penutup monumental yang dikutip oleh para sejarawan ratusan tahun setelahnya.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "C2.7-M11",
    levelId: "C2.7",
    cefr: "C2",
    orderIndex: 89,
    title: "Unit 11: The Sovereign Capstone: 30-Minute Unscripted Dialectical Defense",
    group: "Grandmaster Capstone",
    objective: "Mampu menjalani sidang dialektika 30 menit tanpa naskah menghadapi dewan guru besar penutur asli bahasa Inggris.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "C2.7-M12",
    levelId: "C2.7",
    cefr: "C2",
    orderIndex: 90,
    title: "Unit 12: The Valedictory Oration of the Grandmaster English Speaker",
    group: "Valedictory Oratory",
    objective: "Mampu menyampaikan orasi perpisahan agung yang menandai pencapaian puncak absolut penguasaan bahasa Inggris tingkat dunia.",
    complexity: "deep",
    isExam: false,
  },
  {
    id: "C2.7-M13",
    levelId: "C2.7",
    cefr: "C2",
    orderIndex: 91,
    title: "Ujian Kelulusan C2.7: Evaluasi Pamungkas The Sovereign English Grandmaster (Ultimate Capstone)",
    group: "Grand Graduation",
    objective: "Evaluasi akhir puncak seluruh kurikulum: penguasaan sempurna bahasa Inggris setara intelektual penutur asli dunia.",
    complexity: "deep",
    isExam: true,
  },
];
