export interface ModuleMeta {
  id: string;
  levelId: string;
  orderIndex: number;
  title: string;
  group: string;
  objective: string;
  isExam: boolean;
  passingScore: number;
  promptNotes: string;
}

export const A1_1_EXAM_META: ModuleMeta = {
  id: "A1.1-M13",
  levelId: "A1.1",
  orderIndex: 13,
  title: "Ujian Kelulusan A1.1: Evaluasi Fondasi 4 Keterampilan",
  group: "A1.1 - Starter Foundations",
  objective: "Ujian kelulusan komprehensif 4 keterampilan (Listening, Reading, Writing, Speaking) untuk membuka Sub-Level A1.2",
  isExam: true,
  passingScore: 75,
  promptNotes: "Comprehensive 4-skills foundation exam covering countries/nationalities, to be, family, daily routines, food/drink, time, can/can't, places in town, and past simple was/were. Exactly 16 questions divided into 4 categories: [Listening Comprehension], [Reading Comprehension], [Writing & Grammar], [Speaking & Situational Dialogue].",
};

export const A1_2_SYLLABUS: ModuleMeta[] = [
  {
    id: "A1.2-M01",
    levelId: "A1.2",
    orderIndex: 1,
    title: "Asking for & Giving Directions in the City",
    group: "A1.2 - Daily Logistics & Practical Actions",
    objective: "Mampu menanyakan dan memberi petunjuk arah di dalam kota (turn left, turn right, go straight, next to, opposite)",
    isExam: false,
    passingScore: 70,
    promptNotes: "Prepositions of place and imperative directions: Turn left, turn right, go straight ahead, on your left/right, next to the bank, opposite the supermarket. Dialogue at the city center asking for the train station.",
  },
  {
    id: "A1.2-M02",
    levelId: "A1.2",
    orderIndex: 2,
    title: "Shopping, Prices & Numbers",
    group: "A1.2 - Daily Logistics & Practical Actions",
    objective: "Mampu bertransaksi belanja, menanyakan harga (How much is this/are these?), dan menyebutkan angka harga dengan benar",
    isExam: false,
    passingScore: 70,
    promptNotes: "Shopping dialogues, buying clothes/souvenirs, 'How much is this shirt?', 'How much are these shoes?', prices, currency pounds/dollars/euros, numbers 20-100.",
  },
  {
    id: "A1.2-M03",
    levelId: "A1.2",
    orderIndex: 3,
    title: "Dining Out: Ordering Food & Drinks",
    group: "A1.2 - Daily Logistics & Practical Actions",
    objective: "Mampu memesan makanan dan minuman di restoran atau kafe secara sopan menggunakan 'I would like' dan 'Could I have'",
    isExam: false,
    passingScore: 70,
    promptNotes: "Restaurant language, menu items, table for two, I'd like a chicken sandwich, Could I have some water, please? bill/check please.",
  },
  {
    id: "A1.2-M04",
    levelId: "A1.2",
    orderIndex: 4,
    title: "Clothing, Colors & Weather Descriptions",
    group: "A1.2 - Daily Logistics & Practical Actions",
    objective: "Mampu mendeskripsikan pakaian yang sedang dikenakan dan cuaca hari ini menggunakan Present Continuous (wearing)",
    isExam: false,
    passingScore: 70,
    promptNotes: "Clothes vocabulary (jacket, jeans, shoes, dress, hat), weather adjectives (sunny, rainy, cold, windy, freezing), present continuous: 'She is wearing a yellow raincoat because it is raining.'",
  },
  {
    id: "A1.2-M05",
    levelId: "A1.2",
    orderIndex: 5,
    title: "House, Rooms & Furniture: There is & There are",
    group: "A1.2 - Daily Logistics & Practical Actions",
    objective: "Mampu mendeskripsikan ruangan dan perabotan di dalam rumah menggunakan struktur 'There is' dan 'There are'",
    isExam: false,
    passingScore: 70,
    promptNotes: "Rooms in a house (kitchen, living room, bedroom, bathroom), furniture (sofa, bed, table, fridge, wardrobe), There is a big sofa in the living room. Are there any chairs?",
  },
  {
    id: "A1.2-M06",
    levelId: "A1.2",
    orderIndex: 6,
    title: "Public Transportation & Commuting",
    group: "A1.2 - Daily Logistics & Practical Actions",
    objective: "Mampu bernavigasi menggunakan transportasi umum (bus, kereta, taksi) dan membeli tiket perjalanan",
    isExam: false,
    passingScore: 70,
    promptNotes: "Transportation vocabulary (bus stop, platform, single ticket, return ticket, schedule, delay), 'Which bus goes to the airport?', 'The train departs from platform 3.'",
  },
  {
    id: "A1.2-M07",
    levelId: "A1.2",
    orderIndex: 7,
    title: "Describing Health, Body Parts & Ailments",
    group: "A1.2 - Daily Logistics & Practical Actions",
    objective: "Mampu mengomunikasikan kondisi kesehatan, bagian tubuh, dan rasa sakit umum (I have a headache, stomachache, sore throat)",
    isExam: false,
    passingScore: 70,
    promptNotes: "Body parts (head, stomach, back, arm, leg), health problems (headache, fever, cough, cold, toothache), giving simple advice: 'You should drink warm tea and rest.'",
  },
  {
    id: "A1.2-M08",
    levelId: "A1.2",
    orderIndex: 8,
    title: "Making Plans, Suggestions & Invitations",
    group: "A1.2 - Daily Logistics & Practical Actions",
    objective: "Mampu mengundang teman, membuat janji bertemu, serta menerima atau menolak ajakan secara sopan (Would you like to...?)",
    isExam: false,
    passingScore: 70,
    promptNotes: "Invitations: 'Would you like to come to my party?', 'Let's meet at 5 PM', 'That sounds great! / I'm sorry, I'm busy.' Making suggestions: 'Why don't we watch a movie?'",
  },
  {
    id: "A1.2-M09",
    levelId: "A1.2",
    orderIndex: 9,
    title: "Hobbies & Preferences: Like, Love & Hate + -ing",
    group: "A1.2 - Daily Logistics & Practical Actions",
    objective: "Mampu mengungkapkan hobi dan tingkat kesukaan terhadap suatu aktivitas menggunakan pola verb + gerund (-ing)",
    isExam: false,
    passingScore: 70,
    promptNotes: "Expressing likes and dislikes: I love reading novels, I enjoy playing football, I don't mind washing dishes, I hate waking up early. Gerund spelling rules.",
  },
  {
    id: "A1.2-M10",
    levelId: "A1.2",
    orderIndex: 10,
    title: "Obligations & Rules: Must, Mustn't & Have to",
    group: "A1.2 - Daily Logistics & Practical Actions",
    objective: "Mampu menyatakan aturan, kewajiban, dan larangan di sekolah atau tempat umum menggunakan modal verb 'must' dan 'have to'",
    isExam: false,
    passingScore: 70,
    promptNotes: "Rules and obligations: You must wear a helmet, You mustn't talk in the library, I have to finish my homework before 9 PM, You don't have to pay.",
  },
  {
    id: "A1.2-M11",
    levelId: "A1.2",
    orderIndex: 11,
    title: "Prepositions of Movement: Into, Out of & Across",
    group: "A1.2 - Daily Logistics & Practical Actions",
    objective: "Mampu menggunakan preposisi pergerakan (into, out of, across, through, along, past) untuk menceritakan rute perpindahan",
    isExam: false,
    passingScore: 70,
    promptNotes: "Movement prepositions: The cat ran into the box, He walked across the bridge, They ran through the park, Drive along Main Street.",
  },
  {
    id: "A1.2-M12",
    levelId: "A1.2",
    orderIndex: 12,
    title: "Sharing Weekend Stories: Common Irregular Past Verbs",
    group: "A1.2 - Daily Logistics & Practical Actions",
    objective: "Mampu menceritakan kegiatan akhir pekan yang telah berlalu menggunakan kata kerja lampau tak beraturan (went, saw, had, bought, did)",
    isExam: false,
    passingScore: 70,
    promptNotes: "Irregular past simple verbs: go -> went, see -> saw, have -> had, buy -> bought, do -> did, eat -> ate, meet -> met. Asking 'What did you do last weekend?'",
  },
  {
    id: "A1.2-M13",
    levelId: "A1.2",
    orderIndex: 13,
    title: "Ujian Kelulusan A1.2: Evaluasi Komprehensif 4 Keterampilan",
    group: "A1.2 - Daily Logistics & Practical Actions",
    objective: "Ujian kelulusan komprehensif 4 keterampilan (Listening, Reading, Writing, Speaking) untuk membuka Sub-Level A1.3",
    isExam: true,
    passingScore: 75,
    promptNotes: "Comprehensive 4-skills graduation exam covering direction, shopping, restaurant, transportation, house, health, and past irregular verbs. Must include 16 questions divided into 4 categories: [Listening Comprehension], [Reading Comprehension], [Writing & Grammar], [Speaking & Situational Dialogue].",
  },
];

export const A1_3_SYLLABUS: ModuleMeta[] = [
  {
    id: "A1.3-M01",
    levelId: "A1.3",
    orderIndex: 1,
    title: "Comparative Adjectives: Comparing People & Things",
    group: "A1.3 - Experiences, Comparisons & Future Intentions",
    objective: "Mampu membandingkan dua orang, benda, atau tempat menggunakan bentuk comparative (-er than, more ... than)",
    isExam: false,
    passingScore: 70,
    promptNotes: "Comparatives: taller than, bigger than, more expensive than, easier than, irregular: better, worse. Comparing cities, smartphones, and animals.",
  },
  {
    id: "A1.3-M02",
    levelId: "A1.3",
    orderIndex: 2,
    title: "Superlative Adjectives: The Best & The Most Exciting",
    group: "A1.3 - Experiences, Comparisons & Future Intentions",
    objective: "Mampu menyatakan yang paling/ter- di antara suatu kelompok menggunakan superlative (the -est, the most ...)",
    isExam: false,
    passingScore: 70,
    promptNotes: "Superlatives: the tallest, the biggest, the most interesting, the most famous, the best, the worst. World records, longest river, highest mountain.",
  },
  {
    id: "A1.3-M03",
    levelId: "A1.3",
    orderIndex: 3,
    title: "Holiday Experiences & Travel Memories",
    group: "A1.3 - Experiences, Comparisons & Future Intentions",
    objective: "Mampu menceritakan pengalaman liburan masa lalu secara detail (tujuan, akomodasi, aktivitas, dan kesan)",
    isExam: false,
    passingScore: 70,
    promptNotes: "Vacation vocabulary: hotel, flight, beach, souvenirs, sightseeing. Past simple narratives: 'We stayed at a cozy hotel and visited famous museums. It was incredible!'",
  },
  {
    id: "A1.3-M04",
    levelId: "A1.3",
    orderIndex: 4,
    title: "Future Plans & Intentions with 'Be Going To'",
    group: "A1.3 - Experiences, Comparisons & Future Intentions",
    objective: "Mampu menyampaikan rencana masa depan dan niat yang sudah diputuskan menggunakan struktur 'be going to + verb'",
    isExam: false,
    passingScore: 70,
    promptNotes: "Future intentions: I am going to study abroad, Are you going to visit your grandparents tomorrow? She isn't going to buy that car. Time expressions: tomorrow, next week, tonight.",
  },
  {
    id: "A1.3-M05",
    levelId: "A1.3",
    orderIndex: 5,
    title: "Describing Physical Appearance & Style",
    group: "A1.3 - Experiences, Comparisons & Future Intentions",
    objective: "Mampu mendeskripsikan ciri-ciri fisik seseorang (tinggi badan, warna & model rambut, bentuk wajah, kacamata)",
    isExam: false,
    passingScore: 70,
    promptNotes: "Appearance vocabulary: tall, short, slim, curly hair, straight blonde hair, beard, moustache, wears glasses, brown eyes. Have got vs Be for appearance.",
  },
  {
    id: "A1.3-M06",
    levelId: "A1.3",
    orderIndex: 6,
    title: "Personalities, Character Traits & Feelings",
    group: "A1.3 - Experiences, Comparisons & Future Intentions",
    objective: "Mampu mendeskripsikan sifat kepribadian teman dan suasana hati (cheerful, polite, honest, shy, confident)",
    isExam: false,
    passingScore: 70,
    promptNotes: "Personality adjectives: kind, friendly, helpful, funny, serious, shy, confident, creative. 'Why do you like him? Because he is always generous and polite.'",
  },
  {
    id: "A1.3-M07",
    levelId: "A1.3",
    orderIndex: 7,
    title: "Special Talents & Skills: 'Good at' & 'Bad at'",
    group: "A1.3 - Experiences, Comparisons & Future Intentions",
    objective: "Mampu mengomunikasikan bakat, keahlian khusus, dan hal-hal yang dikuasai dengan baik menggunakan 'good at + -ing'",
    isExam: false,
    passingScore: 70,
    promptNotes: "Talents and skills: I am good at playing the piano, She is brilliant at cooking, He is bad at remembering names. Can vs be good at.",
  },
  {
    id: "A1.3-M08",
    levelId: "A1.3",
    orderIndex: 8,
    title: "Polite Requests, Permission & Offers",
    group: "A1.3 - Experiences, Comparisons & Future Intentions",
    objective: "Mampu meminta izin, meminta bantuan, dan menawarkan sesuatu secara santun (Could you, May I, Shall I)",
    isExam: false,
    passingScore: 70,
    promptNotes: "Polite requests: Could you please open the window? May I borrow your pen? Shall I help you with your bag? Accepting and declining with courtesy.",
  },
  {
    id: "A1.3-M09",
    levelId: "A1.3",
    orderIndex: 9,
    title: "Explaining Reasons & Consequences: 'Because' & 'So'",
    group: "A1.3 - Experiences, Comparisons & Future Intentions",
    objective: "Mampu menghubungkan dua klausa untuk menjelaskan sebab dan akibat dalam percakapan sehari-hari",
    isExam: false,
    passingScore: 70,
    promptNotes: "Cause and effect: I went to bed early because I was exhausted. It was raining, so we stayed home. Asking 'Why?' and answering with 'Because...'",
  },
  {
    id: "A1.3-M10",
    levelId: "A1.3",
    orderIndex: 10,
    title: "Public Signs, Notices & Imperatives",
    group: "A1.3 - Experiences, Comparisons & Future Intentions",
    objective: "Mampu memahami tanda peringatan di tempat umum, rambu keselamatan, dan instruksi langsung (Do not enter, Keep off the grass)",
    isExam: false,
    passingScore: 70,
    promptNotes: "Public signage: Caution wet floor, No smoking, Turn off cell phones, Emergency exit, Push / Pull. Positive and negative imperatives.",
  },
  {
    id: "A1.3-M11",
    levelId: "A1.3",
    orderIndex: 11,
    title: "City Life vs Country Life: Pros & Cons",
    group: "A1.3 - Experiences, Comparisons & Future Intentions",
    objective: "Mampu membandingkan kehidupan di kota besar dengan pedesaan menggunakan argumen sederhana dan kosa kata lingkungan",
    isExam: false,
    passingScore: 70,
    promptNotes: "Urban vs rural living: traffic, pollution, fresh air, peaceful, modern facilities, crowded. 'Cities are busier than villages, but countryside is healthier.'",
  },
  {
    id: "A1.3-M12",
    levelId: "A1.3",
    orderIndex: 12,
    title: "Bridge to A2: Comprehensive Conversational Fluency",
    group: "A1.3 - Experiences, Comparisons & Future Intentions",
    objective: "Mampu menggabungkan masa lalu, sekarang, dan rencana masa depan secara luwes dalam satu alur percakapan utuh",
    isExam: false,
    passingScore: 70,
    promptNotes: "Integration of present, past, and future (be going to). Conversational connectors: also, but, because, so, then, after that. High confidence speaking drill.",
  },
  {
    id: "A1.3-M13",
    levelId: "A1.3",
    orderIndex: 13,
    title: "Ujian Kelulusan Akhir A1: 4-Skills CEFR A1 Graduation Exam",
    group: "A1.3 - Experiences, Comparisons & Future Intentions",
    objective: "Ujian kelulusan akhir CEFR A1 komprehensif 4 keterampilan (Listening, Reading, Writing, Speaking) untuk membuka Level A2",
    isExam: true,
    passingScore: 75,
    promptNotes: "Official CEFR A1 Graduation Exam covering comparisons, vacation memories, future plans (be going to), appearance, character, and reasons. Must include 16 questions divided into 4 categories: [Listening Comprehension], [Reading Comprehension], [Writing & Grammar], [Speaking & Situational Dialogue].",
  },
];
