export interface ModuleMeta {
  id: string;
  levelId: string;
  orderIndex: number;
  title: string;
  group: string;
  objective: string;
  isExam: boolean;
  passingScore: number;
  promptNotes: string;
}

export const A2_1_EXAM_META: ModuleMeta = {
  id: "A2.1-M13",
  levelId: "A2.1",
  orderIndex: 13,
  title: "Ujian Kelulusan A2.1: Evaluasi Komprehensif Tindakan Dasar",
  group: "A2.1 - Elementary Actions",
  objective: "Ujian kelulusan komprehensif 4 keterampilan (Listening, Reading, Writing, Speaking) untuk membuka Sub-Level A2.2",
  isExam: true,
  passingScore: 75,
  promptNotes: "Comprehensive 4-skills elementary exam covering present tenses, past simple, quantifiers (too/enough), comparatives, past continuous, have to, future with will, modals of advice, first conditional, and present perfect with ever/never. Exactly 16 questions divided into 4 categories: [Listening Comprehension], [Reading Comprehension], [Writing & Grammar], [Speaking & Situational Dialogue].",
};

export const A2_2_SYLLABUS: ModuleMeta[] = [
  {
    id: "A2.2-M01",
    levelId: "A2.2",
    orderIndex: 1,
    title: "Professions, Workplaces & Job Responsibilities",
    group: "A2.2 - Social Dynamics, Work & Everyday Life",
    objective: "Mampu menjelaskan profesi, tempat kerja, dan tanggung jawab pekerjaan sehari-hari menggunakan kosakata kerja baku",
    isExam: false,
    passingScore: 70,
    promptNotes: "Professions (architect, electrician, journalist, nurse, flight attendant), workplace verbs (manage, design, repair, care for, operate), 'What does an architect do? An architect designs buildings.'",
  },
  {
    id: "A2.2-M02",
    levelId: "A2.2",
    orderIndex: 2,
    title: "Spontaneous Decisions vs Intentions: Will vs Be Going To",
    group: "A2.2 - Social Dynamics, Work & Everyday Life",
    objective: "Mampu membedakan keputusan spontan (will) dengan rencana/niat yang telah disiapkan (be going to)",
    isExam: false,
    passingScore: 70,
    promptNotes: "Contrast will vs be going to: 'The phone is ringing. I'll get it!' vs 'I'm going to study engineering next year.' Offers and promises with will.",
  },
  {
    id: "A2.2-M03",
    levelId: "A2.2",
    orderIndex: 3,
    title: "Life Milestones & Experiences with Present Perfect: Just, Already & Yet",
    group: "A2.2 - Social Dynamics, Work & Everyday Life",
    objective: "Mampu menyampaikan pencapaian hidup dan aktivitas terkini menggunakan Present Perfect dengan 'just', 'already', dan 'yet'",
    isExam: false,
    passingScore: 70,
    promptNotes: "Present perfect adverbs: I have just finished my lunch, She has already passed her driving test, Have you seen the new movie yet? No, I haven't watched it yet.",
  },
  {
    id: "A2.2-M04",
    levelId: "A2.2",
    orderIndex: 4,
    title: "Movies, Cinema & Expressing Critical Opinions",
    group: "A2.2 - Social Dynamics, Work & Everyday Life",
    objective: "Mampu mendiskusikan genre film, plot cerita, dan mengemukakan opini kritis menggunakan kata sifat evaluatif",
    isExam: false,
    passingScore: 70,
    promptNotes: "Movie genres (action, documentary, comedy, sci-fi, animated), opinion phrases (In my opinion, I found it..., The plot was thrilling, boring, predictable, brilliant), recommending a film.",
  },
  {
    id: "A2.2-M05",
    levelId: "A2.2",
    orderIndex: 5,
    title: "Culinary Traditions, Recipes & Kitchen Verbs",
    group: "A2.2 - Social Dynamics, Work & Everyday Life",
    objective: "Mampu menjelaskan langkah memasak, bahan resep, dan tradisi kuliner menggunakan kata kerja dapur yang tepat",
    isExam: false,
    passingScore: 70,
    promptNotes: "Kitchen verbs (chop, slice, boil, fry, bake, stir, mix), recipe sequence (first, next, then, finally), ingredients, measurements (tablespoon, cup, gram). Traditional dish explanation.",
  },
  {
    id: "A2.2-M06",
    levelId: "A2.2",
    orderIndex: 6,
    title: "Materials, Textures & Possessions: Whose is this?",
    group: "A2.2 - Social Dynamics, Work & Everyday Life",
    objective: "Mampu mendeskripsikan bahan pembuat benda (made of leather, wood, glass) dan menanyakan kepemilikan (whose)",
    isExam: false,
    passingScore: 70,
    promptNotes: "Materials (leather, cotton, plastic, metal, wood, wool, glass), 'What is it made of?', 'Whose jacket is this? It's mine / It belongs to Sarah.' Possessive pronouns (mine, yours, his, hers, ours, theirs).",
  },
  {
    id: "A2.2-M07",
    levelId: "A2.2",
    orderIndex: 7,
    title: "Everyday Emergencies, Lost Property & Reporting Incidents",
    group: "A2.2 - Social Dynamics, Work & Everyday Life",
    objective: "Mampu melaporkan kehilangan barang berharga dan merespons situasi darurat ringan di tempat umum secara jelas",
    isExam: false,
    passingScore: 70,
    promptNotes: "Reporting lost items: 'I've lost my passport/backpack', describing the item (color, size, brand, contents), filling in a lost property form, asking for help at customer service or police desk.",
  },
  {
    id: "A2.2-M08",
    levelId: "A2.2",
    orderIndex: 8,
    title: "Music Genres, Concerts & Booking Event Tickets",
    group: "A2.2 - Social Dynamics, Work & Everyday Life",
    objective: "Mampu berinteraksi dalam pemesanan tiket pertunjukan musik dan mengekspresikan selera seni secara santun",
    isExam: false,
    passingScore: 70,
    promptNotes: "Music vocabulary (live concert, venue, stage, audience, acoustic, electric), booking tickets dialogue: 'Are there any seats available for Friday night?', price inquiry, payment method.",
  },
  {
    id: "A2.2-M09",
    levelId: "A2.2",
    orderIndex: 9,
    title: "Airport Logistics, Flights & Hotel Reservations",
    group: "A2.2 - Social Dynamics, Work & Everyday Life",
    objective: "Mampu menavigasi alur perjalanan udara (check-in, boarding gate, luggage claim) dan reservasi akomodasi hotel",
    isExam: false,
    passingScore: 70,
    promptNotes: "Airport procedures: check-in desk, hand luggage, boarding pass, passport control, gate announcement. Hotel check-in: double room, breakfast included, key card, checkout time.",
  },
  {
    id: "A2.2-M10",
    levelId: "A2.2",
    orderIndex: 10,
    title: "Giving Lifestyle Advice: Should, Shouldn't & Ought To",
    group: "A2.2 - Social Dynamics, Work & Everyday Life",
    objective: "Mampu memberikan saran dan rekomendasi gaya hidup sehat menggunakan modal verbs 'should', 'shouldn't', dan 'ought to'",
    isExam: false,
    passingScore: 70,
    promptNotes: "Advice modals: You should sleep at least 7 hours, You shouldn't drink too much caffeine, You ought to exercise regularly. Asking for advice: 'What should I do?'",
  },
  {
    id: "A2.2-M11",
    levelId: "A2.2",
    orderIndex: 11,
    title: "Narrative Time: Past Continuous Interrupted by Past Simple",
    group: "A2.2 - Social Dynamics, Work & Everyday Life",
    objective: "Mampu merangkai cerita masa lalu di mana sebuah peristiwa sedang berlangsung lalu disela oleh kejadian lain (when/while)",
    isExam: false,
    passingScore: 70,
    promptNotes: "Past continuous + past simple with when and while: 'I was walking in the park when it suddenly started to snow.' 'While we were having dinner, the lights went out.'",
  },
  {
    id: "A2.2-M12",
    levelId: "A2.2",
    orderIndex: 12,
    title: "Friendship Qualities, Conflicts & Apologizing Sincerely",
    group: "A2.2 - Social Dynamics, Work & Everyday Life",
    objective: "Mampu mengomunikasikan kualitas pertemanan, menyelesaikan kesalahpahaman, dan meminta maaf secara tulus",
    isExam: false,
    passingScore: 70,
    promptNotes: "Friendship phrases: get on well with, rely on, have an argument, make up, forgive. Apologizing: 'I'm really sorry for being late. I didn't mean to upset you.' Accepting apologies politely.",
  },
  {
    id: "A2.2-M13",
    levelId: "A2.2",
    orderIndex: 13,
    title: "Ujian Kelulusan A2.2: Evaluasi Komprehensif Dinamika Sosial",
    group: "A2.2 - Social Dynamics, Work & Everyday Life",
    objective: "Ujian kelulusan komprehensif 4 keterampilan (Listening, Reading, Writing, Speaking) untuk membuka Sub-Level A2.3",
    isExam: true,
    passingScore: 75,
    promptNotes: "Comprehensive 4-skills graduation exam covering professions, future plans, present perfect adverbs, recipes, airport travel, advice (should), and past narrative tenses. Exactly 16 questions divided into 4 categories: [Listening Comprehension], [Reading Comprehension], [Writing & Grammar], [Speaking & Situational Dialogue].",
  },
];

export const A2_3_SYLLABUS: ModuleMeta[] = [
  {
    id: "A2.3-M01",
    levelId: "A2.3",
    orderIndex: 1,
    title: "Extreme Weather Phenomena & Safety Procedures",
    group: "A2.3 - World Explorations, Stories & Bridge to B1",
    objective: "Mampu memahami dan mendiskusikan fenomena cuaca ekstrem serta instruksi keselamatan darurat",
    isExam: false,
    passingScore: 70,
    promptNotes: "Weather extremes: hurricane, blizzard, flood, earthquake, heatwave. Safety commands: stay indoors, evacuate immediately, turn off electricity. Emergency broadcast comprehension.",
  },
  {
    id: "A2.3-M02",
    levelId: "A2.3",
    orderIndex: 2,
    title: "First Conditional: Realistic Causes and Real-life Consequences",
    group: "A2.3 - World Explorations, Stories & Bridge to B1",
    objective: "Mampu menggunakan First Conditional (If + Present Simple, will + verb) untuk memprediksi konsekuensi realistis di masa depan",
    isExam: false,
    passingScore: 70,
    promptNotes: "First conditional patterns: 'If you study hard, you will pass the exam.' 'Unless we leave now, we will miss the train.' Negotiation and realistic promises.",
  },
  {
    id: "A2.3-M03",
    levelId: "A2.3",
    orderIndex: 3,
    title: "Modern Digital Habits & Online Cybersecurity Basics",
    group: "A2.3 - World Explorations, Stories & Bridge to B1",
    objective: "Mampu membicarakan kebiasaan digital, media sosial, dan aturan keamanan berselancar di internet",
    isExam: false,
    passingScore: 70,
    promptNotes: "Digital habits: screen time, password security, privacy settings, verify links, avoid scams, attach files. 'You should never share your password with anyone.'",
  },
  {
    id: "A2.3-M04",
    levelId: "A2.3",
    orderIndex: 4,
    title: "Storytelling Techniques: Chronological Connectors & Suspense",
    group: "A2.3 - World Explorations, Stories & Bridge to B1",
    objective: "Mampu menceritakan narasi yang menarik dan terstruktur menggunakan kata hubung kronologis (At first, suddenly, meanwhile, in the end)",
    isExam: false,
    passingScore: 70,
    promptNotes: "Narrative connectors: At first, suddenly, unexpectedly, meanwhile, eventually, in the end. Building suspense in storytelling and engaging the listener.",
  },
  {
    id: "A2.3-M05",
    levelId: "A2.3",
    orderIndex: 5,
    title: "Architectural Wonders & Historic Landmarks",
    group: "A2.3 - World Explorations, Stories & Bridge to B1",
    objective: "Mampu mendeskripsikan bangunan bersejarah, monumen budaya, dan keajaiban arsitektur dunia secara detail",
    isExam: false,
    passingScore: 70,
    promptNotes: "Architecture vocabulary: ancient temple, skyscraper, dome, stone bridge, century-old fortress, tourist attraction. Describing year built, location, and significance.",
  },
  {
    id: "A2.3-M06",
    levelId: "A2.3",
    orderIndex: 6,
    title: "Imaginary Scenarios: Introduction to Second Conditional",
    group: "A2.3 - World Explorations, Stories & Bridge to B1",
    objective: "Mampu mengutarakan situasi imajiner dan impian masa depan menggunakan Second Conditional (If + Past Simple, would + verb)",
    isExam: false,
    passingScore: 70,
    promptNotes: "Second conditional intro: 'If I had a million dollars, I would travel the world.' 'If I were you, I would take the job.' Talking about hypothetical dreams and wishes.",
  },
  {
    id: "A2.3-M07",
    levelId: "A2.3",
    orderIndex: 7,
    title: "Environmental Conservation, Eco-habits & Wildlife Protection",
    group: "A2.3 - World Explorations, Stories & Bridge to B1",
    objective: "Mampu mendiskusikan isu lingkungan, kebiasaan ramah lingkungan, dan perlindungan satwa langka",
    isExam: false,
    passingScore: 70,
    promptNotes: "Eco vocabulary: recycle plastic, reduce waste, renewable energy, endangered species, rainforest, habitat loss. 'We can protect nature by using public transit.'",
  },
  {
    id: "A2.3-M08",
    levelId: "A2.3",
    orderIndex: 8,
    title: "Then vs Now: Comparing Eras with 'Used To'",
    group: "A2.3 - World Explorations, Stories & Bridge to B1",
    objective: "Mampu membandingkan kebiasaan masa lalu yang sudah tidak dilakukan lagi menggunakan struktur 'used to + verb'",
    isExam: false,
    passingScore: 70,
    promptNotes: "Used to for past habits and states: 'People used to write handwritten letters, but now they send instant messages.' 'Did you use to play video games as a child?'",
  },
  {
    id: "A2.3-M09",
    levelId: "A2.3",
    orderIndex: 9,
    title: "Essential Daily Phrasal Verbs in Context",
    group: "A2.3 - World Explorations, Stories & Bridge to B1",
    objective: "Mampu menggunakan kata kerja frasa populer (turn on/off, look after, give up, find out, run out of) dalam percakapan natural",
    isExam: false,
    passingScore: 70,
    promptNotes: "Common phrasal verbs: wake up, turn on/off, look after, give up, find out, run out of, put on, take off. Natural context in daily situations.",
  },
  {
    id: "A2.3-M10",
    levelId: "A2.3",
    orderIndex: 10,
    title: "Defining Relative Clauses: Who, Which, That & Where",
    group: "A2.3 - World Explorations, Stories & Bridge to B1",
    objective: "Mampu menggabungkan dua informasi menjadi satu kalimat kompleks menggunakan kata ganti relatif (who, which, that, where)",
    isExam: false,
    passingScore: 70,
    promptNotes: "Defining relative clauses: 'A teacher is someone who helps students.' 'A museum is a place where you see historic relics.' 'I bought a smartphone that takes great photos.'",
  },
  {
    id: "A2.3-M11",
    levelId: "A2.3",
    orderIndex: 11,
    title: "Polite Agreement & Constructive Disagreement",
    group: "A2.3 - World Explorations, Stories & Bridge to B1",
    objective: "Mampu menyetujui (So do I, Neither do I) atau menyanggah pendapat orang lain secara santun dan konstruktif",
    isExam: false,
    passingScore: 70,
    promptNotes: "Agreement & disagreement: So do I, Neither do I, I totally agree, That's a valid point, but..., I see what you mean, however... Discussing hobbies and daily choices.",
  },
  {
    id: "A2.3-M12",
    levelId: "A2.3",
    orderIndex: 12,
    title: "Bridge to B1: Spontaneous Fluency & Extended Responses",
    group: "A2.3 - World Explorations, Stories & Bridge to B1",
    objective: "Mampu memberikan jawaban panjang, merangkai argumen dengan alasan, dan merespons pertanyaan tak terduga secara lancar",
    isExam: false,
    passingScore: 70,
    promptNotes: "Bridge to B1 fluency: Extended answers (Point + Reason + Example), discourse markers (Actually, Honestly, Well, To be fair), handling conversational transitions smoothly.",
  },
  {
    id: "A2.3-M13",
    levelId: "A2.3",
    orderIndex: 13,
    title: "Ujian Kelulusan Akhir A2: 4-Skills CEFR A2 Graduation Exam",
    group: "A2.3 - World Explorations, Stories & Bridge to B1",
    objective: "Ujian kelulusan akhir CEFR A2 komprehensif 4 keterampilan (Listening, Reading, Writing, Speaking) untuk membuka Level B1",
    isExam: true,
    passingScore: 75,
    promptNotes: "Official CEFR A2 Graduation Exam covering conditionals (1st & 2nd intro), used to, relative clauses, phrasal verbs, eco-issues, and extended narrative fluency. Exactly 16 questions divided into 4 categories: [Listening Comprehension], [Reading Comprehension], [Writing & Grammar], [Speaking & Situational Dialogue].",
  },
];
