export interface ModuleMeta {
  id: string;
  levelId: string;
  title: string;
  group: string;
  objective: string;
  orderIndex: number;
  isExam: boolean;
  passingScore: number;
  promptNotes: string;
}

export const B2_1_EXAM_META: ModuleMeta = {
  id: "B2.1-M13",
  levelId: "B2.1",
  title: "Ujian Kelulusan B2.1: Evaluasi Komprehensif Vantage Foundations",
  group: "B2.1 - Vantage Foundations",
  objective:
    "Ujian kelulusan komprehensif 4 keterampilan (Listening, Reading, Writing, Speaking) untuk membuka Sub-Level B2.2",
  orderIndex: 13,
  isExam: true,
  passingScore: 75,
  promptNotes:
    "Ujian komprehensif 4-Skills B2.1: 16 butir soal (4 Listening transkrip audio, 4 Reading artikel, 4 Writing/Grammar, 4 Speaking roleplay/debat). Topik: narrative tenses, modals of deduction, passives, conditionals.",
};

export const B2_2_SYLLABUS: ModuleMeta[] = [
  {
    id: "B2.2-M01",
    levelId: "B2.2",
    title: "Corporate Governance, Ethics & Whistleblowing Policies",
    group: "B2.2 - Advanced Professional & Academic Fluency",
    objective: "Mendiskusikan etika korporasi, tanggung jawab hukum perusahaan, dan perlindungan pelapor pelanggaran.",
    orderIndex: 1,
    isExam: false,
    passingScore: 70,
    promptNotes: "Corporate ethics vocabulary, legal accountability, formal debate structures.",
  },
  {
    id: "B2.2-M02",
    levelId: "B2.2",
    title: "Advanced Inversion for Dramatic Emphasis & Formal Oratory",
    group: "B2.2 - Advanced Professional & Academic Fluency",
    objective: "Menguasai struktur inversi negatif (Never have I..., Seldom do we..., Not only... but also...).",
    orderIndex: 2,
    isExam: false,
    passingScore: 70,
    promptNotes: "Negative adverbial inversion formula, oratorical power, common syntax pitfalls.",
  },
  {
    id: "B2.2-M03",
    levelId: "B2.2",
    title: "Global Supply Chains, Geopolitics & Logistics Crisis Management",
    group: "B2.2 - Advanced Professional & Academic Fluency",
    objective: "Menganalisis disrupsi rantai pasok global, embargo dagang, dan manajemen krisis transportasi internasional.",
    orderIndex: 3,
    isExam: false,
    passingScore: 70,
    promptNotes: "Logistics terminology, geopolitical risk assessment, contingency planning.",
  },
  {
    id: "B2.2-M04",
    levelId: "B2.2",
    title: "Causative Verbs & Passive Reporting Structures: Have/Get Something Done & It is Alleged",
    group: "B2.2 - Advanced Professional & Academic Fluency",
    objective: "Menggunakan bentuk kausatif dan struktur pasif impersonal untuk pelaporan berita dan investigasi.",
    orderIndex: 4,
    isExam: false,
    passingScore: 70,
    promptNotes: "Causative have/get, impersonal passives: It is believed that / Subject is reported to have done.",
  },
  {
    id: "B2.2-M05",
    levelId: "B2.2",
    title: "Bioethics, Genetic Engineering & Medical Innovations",
    group: "B2.2 - Advanced Professional & Academic Fluency",
    objective: "Mendiskusikan implikasi etis manipulasi genetik, kloning, dan teknologi medis mutakhir.",
    orderIndex: 5,
    isExam: false,
    passingScore: 70,
    promptNotes: "Bioethical debates, balanced argumentation, scientific nuance.",
  },
  {
    id: "B2.2-M06",
    levelId: "B2.2",
    title: "Subjunctive Mood & Formal Demands: It is Vital That He Be Informed",
    group: "B2.2 - Advanced Professional & Academic Fluency",
    objective: "Menguasai penggunaan subjunctive mood dalam resolusi resmi, rekomendasi mendesak, dan protokol hukum.",
    orderIndex: 6,
    isExam: false,
    passingScore: 70,
    promptNotes: "Present subjunctive bare infinitive rules: insist that, recommend that, vital that.",
  },
  {
    id: "B2.2-M07",
    levelId: "B2.2",
    title: "Financial Markets, Risk Hedging & Macroeconomic Indicators",
    group: "B2.2 - Advanced Professional & Academic Fluency",
    objective: "Memahami analisa inflasi, suku bunga acuan bank sentral, portofolio investasi, dan fluktuasi mata uang.",
    orderIndex: 7,
    isExam: false,
    passingScore: 70,
    promptNotes: "Economic trends, chart interpretation, fiscal policy commentary.",
  },
  {
    id: "B2.2-M08",
    levelId: "B2.2",
    title: "Participle Clauses for Concise Writing & Narrative Flow",
    group: "B2.2 - Advanced Professional & Academic Fluency",
    objective: "Menyingkat klausa adverbial menggunakan present and past participle clauses (Having finished, Seen from above).",
    orderIndex: 8,
    isExam: false,
    passingScore: 70,
    promptNotes: "Present/past/perfect participle clauses, avoiding dangling participles.",
  },
  {
    id: "B2.2-M09",
    levelId: "B2.2",
    title: "Artificial Intelligence, Automation & The Future of Human Labor",
    group: "B2.2 - Advanced Professional & Academic Fluency",
    objective: "Mendebat transformasi pasar tenaga kerja akibat AI, otomatisasi cerdas, dan pergeseran keahlian manusia.",
    orderIndex: 9,
    isExam: false,
    passingScore: 70,
    promptNotes: "Labor economics, technological disruption, ethical workforce adaptation.",
  },
  {
    id: "B2.2-M10",
    levelId: "B2.2",
    title: "Complex Phrasal Verbs & Prepositional Combinations in Executive Discourse",
    group: "B2.2 - Advanced Professional & Academic Fluency",
    objective: "Menguasai frasa kerja idiomatis dan kolokasi preposisi tingkat mahir dalam konteks eksekutif.",
    orderIndex: 10,
    isExam: false,
    passingScore: 70,
    promptNotes: "Nuanced business idioms: iron out, boil down to, branch out, factor in.",
  },
  {
    id: "B2.2-M11",
    levelId: "B2.2",
    title: "Negotiation Tactics: Concessions, Leverage & Overcoming Deadlocks",
    group: "B2.2 - Advanced Professional & Academic Fluency",
    objective: "Menerapkan taktik tawar-menawar strategis, memberikan konsesi kondisional, dan memecahkan kebuntuan perundingan.",
    orderIndex: 11,
    isExam: false,
    passingScore: 70,
    promptNotes: "Diplomatic bargaining: conditional concession phrases, win-win framing.",
  },
  {
    id: "B2.2-M12",
    levelId: "B2.2",
    title: "Academic Paper Deconstruction: Abstract Writing, Literature Review & Citation Registers",
    group: "B2.2 - Advanced Professional & Academic Fluency",
    objective: "Menyusun ringkasan penelitian akademik, meninjau literatur, dan mengutip bukti secara ilmiah.",
    orderIndex: 12,
    isExam: false,
    passingScore: 70,
    promptNotes: "Scholarly syntax, hedging in academic prose (suggests, indicates, appears to).",
  },
  {
    id: "B2.2-M13",
    levelId: "B2.2",
    title: "Ujian Kelulusan B2.2: Evaluasi Komprehensif Keberfasihan Profesional & Akademik",
    group: "B2.2 - Advanced Professional & Academic Fluency",
    objective: "Ujian kelulusan komprehensif 4 keterampilan (Listening, Reading, Writing, Speaking) untuk membuka Sub-Level B2.3",
    orderIndex: 13,
    isExam: true,
    passingScore: 75,
    promptNotes: "Ujian 4-Skills B2.2: 16 butir soal (4 Listening negosiasi & krisis bisnis, 4 Reading artikel AI & bioetika, 4 Writing/Grammar inversion, subjunctive, causative, participle clauses, 4 Speaking debat eksekutif).",
  },
];

export const B2_3_SYLLABUS: ModuleMeta[] = [
  {
    id: "B2.3-M01",
    levelId: "B2.3",
    title: "Architectural Philosophy, Urban Planning & Sustainable Megacities",
    group: "B2.3 - Strategic Debate & Bridge to C1",
    objective: "Membahas konsep tata kota megapolitan, zonasi lingkungan, dan estetika arsitektur berkelanjutan.",
    orderIndex: 1,
    isExam: false,
    passingScore: 70,
    promptNotes: "Urban planning lexicon, spatial dynamics, environmental retrofitting.",
  },
  {
    id: "B2.3-M02",
    levelId: "B2.3",
    title: "Cleft Sentences for Rhetorical Precision & Thematic Highlighting",
    group: "B2.3 - Strategic Debate & Bridge to C1",
    objective: "Menggunakan cleft sentences (It is... that, What we need is..., All they wanted was...) untuk penekanan retoris.",
    orderIndex: 2,
    isExam: false,
    passingScore: 70,
    promptNotes: "It-cleft and wh-cleft sentence structures, persuasive focal point positioning.",
  },
  {
    id: "B2.3-M03",
    levelId: "B2.3",
    title: "Behavioral Economics, Cognitive Biases & Consumer Nudging",
    group: "B2.3 - Strategic Debate & Bridge to C1",
    objective: "Menganalisis bias kognitif dalam pengambilan keputusan finansial dan strategi nudging dalam kebijakan publik.",
    orderIndex: 3,
    isExam: false,
    passingScore: 70,
    promptNotes: "Behavioral science terms: loss aversion, anchoring effect, default choice architecture.",
  },
  {
    id: "B2.3-M04",
    levelId: "B2.3",
    title: "Modals of Deduction in the Past: Must have, Could have, Couldn't have, May have been",
    group: "B2.3 - Strategic Debate & Bridge to C1",
    objective: "Merekonstruksi peristiwa masa lalu dengan spekulasi logis dan analisis probabilitas retrospektif.",
    orderIndex: 4,
    isExam: false,
    passingScore: 70,
    promptNotes: "Past modal deduction formulas: modal + have + past participle, distinguishing certainty vs doubt.",
  },
  {
    id: "B2.3-M05",
    levelId: "B2.3",
    title: "Space Exploration, Extraterrestrial Resources & International Treaties",
    group: "B2.3 - Strategic Debate & Bridge to C1",
    objective: "Mendebat eksplorasi luar angkasa, penambangan asteroid, dan hukum kepemilikan teritori antariksa.",
    orderIndex: 5,
    isExam: false,
    passingScore: 70,
    promptNotes: "Astrophysics & space diplomacy vocabulary, treaty interpretation.",
  },
  {
    id: "B2.3-M06",
    levelId: "B2.3",
    title: "Concession & Contrast Connectors in Academic Argumentation",
    group: "B2.3 - Strategic Debate & Bridge to C1",
    objective: "Menguasai konjungsi konsesi tingkat tinggi (Albeit, In spite of, Notwithstanding, Whereas, On the contrary).",
    orderIndex: 6,
    isExam: false,
    passingScore: 70,
    promptNotes: "Advanced concession discourse markers, punctuation and clause placement.",
  },
  {
    id: "B2.3-M07",
    levelId: "B2.3",
    title: "Literary Devices, Subtext & Analyzing Irony in Modern Fiction",
    group: "B2.3 - Strategic Debate & Bridge to C1",
    objective: "Menginterpretasikan makna tersirat, metafora mendalam, ironi situasional, dan sudut pandang narator.",
    orderIndex: 7,
    isExam: false,
    passingScore: 70,
    promptNotes: "Literary analysis vocabulary: allegory, dramatic irony, unreliable narrator.",
  },
  {
    id: "B2.3-M08",
    levelId: "B2.3",
    title: "Ellipsis, Substitution & Fronting for Stylistic Elegance",
    group: "B2.3 - Strategic Debate & Bridge to C1",
    objective: "Menulis kalimat yang ringkas dan bergaya dengan elipsis, substitusi gramatikal, dan fronting objek/adverbial.",
    orderIndex: 8,
    isExam: false,
    passingScore: 70,
    promptNotes: "Stylistic fronting: Up went the prices; Hard though it was; Nominal substitution.",
  },
  {
    id: "B2.3-M09",
    levelId: "B2.3",
    title: "Crisis Diplomacy, Conflict Resolution & International Arbitration",
    group: "B2.3 - Strategic Debate & Bridge to C1",
    objective: "Mendiskusikan sengketa perbatasan, perundingan damai internasional, dan mekanisme arbitrasi netral.",
    orderIndex: 9,
    isExam: false,
    passingScore: 70,
    promptNotes: "Diplomatic protocol, neutrality preservation, multilateral negotiations.",
  },
  {
    id: "B2.3-M10",
    levelId: "B2.3",
    title: "Complex Nominalization: Transforming Verbs and Adjectives into Dense Academic Nouns",
    group: "B2.3 - Strategic Debate & Bridge to C1",
    objective: "Mengubah konstruksi klausa verbal menjadi frasa benda akademik yang padat dan berbobot ilmiah.",
    orderIndex: 10,
    isExam: false,
    passingScore: 70,
    promptNotes: "Nominalization techniques for scientific abstracts and executive briefs.",
  },
  {
    id: "B2.3-M11",
    levelId: "B2.3",
    title: "Oxford Union Style Debate: Parliamentary Rules, Rebuttals & Point of Information",
    group: "B2.3 - Strategic Debate & Bridge to C1",
    objective: "Menguasai struktur debat parlementer, intrupsi santun (POI), sanggahan tajam, dan pidato penutup.",
    orderIndex: 11,
    isExam: false,
    passingScore: 70,
    promptNotes: "Parliamentary debating conventions, strategic refutation techniques.",
  },
  {
    id: "B2.3-M12",
    levelId: "B2.3",
    title: "Bridge to C1: Mastering Spontaneous Synthesis & Nuanced Idiomatic Mastery",
    group: "B2.3 - Strategic Debate & Bridge to C1",
    objective: "Mempersiapkan transisi ke level Effective Operational Proficiency (C1) dengan sintesis ide spontan dan intonasi presisi.",
    orderIndex: 12,
    isExam: false,
    passingScore: 70,
    promptNotes: "C1 transition competencies: multifaceted topic synthesis, pragmatic nuance, idiomatic ease.",
  },
  {
    id: "B2.3-M13",
    levelId: "B2.3",
    title: "Ujian Kelulusan Akhir B2: Comprehensive 4-Skills CEFR B2 Graduation Exam",
    group: "B2.3 - Strategic Debate & Bridge to C1",
    objective: "Ujian kelulusan akhir komprehensif 4 keterampilan (Listening, Reading, Writing, Speaking) untuk membuka Level C1 (C1.1)",
    orderIndex: 13,
    isExam: true,
    passingScore: 75,
    promptNotes: "Ujian akhir CEFR B2: 16 butir soal (4 Listening kuliah tamu & debat diplomasi, 4 Reading artikel ekonomi perilaku & riset megapolitan, 4 Writing/Grammar clefts, past modals, nominalization, inversion, 4 Speaking debat gaya Oxford bersama Mr. Khoirul).",
  },
];
