export interface ModuleMeta {
  id: string;
  levelId: string;
  title: string;
  group: string;
  objective: string;
  orderIndex: number;
  isExam: boolean;
  passingScore: number;
  promptNotes: string;
}

export const C1_1_EXAM_META: ModuleMeta = {
  id: "C1.1-M13",
  levelId: "C1.1",
  title: "Ujian Kelulusan C1.1: Evaluasi Komprehensif Advanced Foundations",
  group: "C1.1 - Advanced Academic & Operational Fluency",
  objective:
    "Ujian kelulusan komprehensif 4 keterampilan (Listening, Reading, Writing, Speaking) untuk membuka Sub-Level C1.2",
  orderIndex: 13,
  isExam: true,
  passingScore: 75,
  promptNotes:
    "Ujian komprehensif 4-Skills C1.1: 16 butir soal (4 Listening transkrip akademis, 4 Reading artikel saintifik/sastra, 4 Writing/Syntax precision, 4 Speaking argumen diplomatik). Topik: gerunds vs infinitives, relative clauses, future tenses, modals of deduction, participle clauses, emphatic structures.",
};

export const C1_2_SYLLABUS: ModuleMeta[] = [
  {
    id: "C1.2-M01",
    levelId: "C1.2",
    title: "Advanced Academic Hedging & Nuanced Modality",
    group: "C1.2 - Strategic Oratory & Complex Syntax",
    objective: "Menguasai teknik hedging akademis (it would appear that, arguably, conceivably, tends to suggest) untuk memaparkan klaim saintifik secara terukur.",
    orderIndex: 1,
    isExam: false,
    passingScore: 70,
    promptNotes: "Academic hedging vocabulary, epistemic adverbs, cautious claim construction, avoiding overgeneralisation.",
  },
  {
    id: "C1.2-M02",
    levelId: "C1.2",
    title: "Complex Nominalisation in Formal Academic & Technical Writing",
    group: "C1.2 - Strategic Oratory & Complex Syntax",
    objective: "Mengubah klausa verbal panjang menjadi frasa nomina padat berbobot tinggi untuk penulisan artikel ilmiah dan jurnal internasional.",
    orderIndex: 2,
    isExam: false,
    passingScore: 70,
    promptNotes: "Nominalisation patterns, information density, lexical packeting, academic register elevation.",
  },
  {
    id: "C1.2-M03",
    levelId: "C1.2",
    title: "Discursive Essays & Counter-Argumentation Architectures",
    group: "C1.2 - Strategic Oratory & Complex Syntax",
    objective: "Menyusun arsitektur esai diskursif tingkat lanjut: konsesi, refutasi antitesis, dan sintesis dialektis yang kokoh.",
    orderIndex: 3,
    isExam: false,
    passingScore: 70,
    promptNotes: "Concession markers: albeit, notwithstanding, even granting that. Structuring persuasive essay bodies.",
  },
  {
    id: "C1.2-M04",
    levelId: "C1.2",
    title: "Advanced Subjunctive Mood & Formulaic Legal Registers",
    group: "C1.2 - Strategic Oratory & Complex Syntax",
    objective: "Menguasai subjunctive formulaik (be that as it may, come what may, lest he fail) dalam register hukum dan protokol formal.",
    orderIndex: 4,
    isExam: false,
    passingScore: 70,
    promptNotes: "Formulaic subjunctive expressions, mandative subjunctive with modal inversion, statutory drafting syntax.",
  },
  {
    id: "C1.2-M05",
    levelId: "C1.2",
    title: "Fronting & Topicalisation for Dramatic Emphasis in Written Rhetoric",
    group: "C1.2 - Strategic Oratory & Complex Syntax",
    objective: "Menggunakan teknik fronting (adverbial, prepositional, adjectival fronting) untuk menciptakan ritme retoris dan fokus wacana.",
    orderIndex: 5,
    isExam: false,
    passingScore: 70,
    promptNotes: "Fronted adverbials with subject-verb inversion, informational packaging, dramatic cadence.",
  },
  {
    id: "C1.2-M06",
    levelId: "C1.2",
    title: "Subtle Cohesion Devices: Anaphora, Cataphora & Ellipsis in Sophisticated Prose",
    group: "C1.2 - Strategic Oratory & Complex Syntax",
    objective: "Memahami rantai kohesi tekstual mikro melalui anafora, katafora, substitusi leksikal, dan elipsis yang elegan.",
    orderIndex: 6,
    isExam: false,
    passingScore: 70,
    promptNotes: "Textual cohesion, cataphoric reference for suspense, structural ellipsis without ambiguity.",
  },
  {
    id: "C1.2-M07",
    levelId: "C1.2",
    title: "Register Variation: Shifting from Colloquial Idiom to High-Formal Academic Registers",
    group: "C1.2 - Strategic Oratory & Complex Syntax",
    objective: "Menganalisis perbedaan tajam antara bahasa percakapan informal, jurnalisme berbobot, dan register akademik kelas atas.",
    orderIndex: 7,
    isExam: false,
    passingScore: 70,
    promptNotes: "Register switching, sociolinguistic appropriateness, lexical elevation, formality spectrum.",
  },
  {
    id: "C1.2-M08",
    levelId: "C1.2",
    title: "Professional Negotiation, Tactful Concession & Strategic Compromise",
    group: "C1.2 - Strategic Oratory & Complex Syntax",
    objective: "Menerapkan ekspresi negosiasi diplomatik tingkat tinggi: penolakan terselubung, tawaran bersyarat, dan pengamanan konsensus.",
    orderIndex: 8,
    isExam: false,
    passingScore: 70,
    promptNotes: "Diplomatic hedging, conditional agreements: provided that, on the proviso that, tactful disagreement.",
  },
  {
    id: "C1.2-M09",
    levelId: "C1.2",
    title: "Critique of Quantitative Research, Statistical Claims & Logical Fallacies",
    group: "C1.2 - Strategic Oratory & Complex Syntax",
    objective: "Mengevaluasi metodologi riset saintifik, mendeteksi bias sampel, korelasi palsu (spurious correlations), dan falasi logika.",
    orderIndex: 9,
    isExam: false,
    passingScore: 70,
    promptNotes: "Empirical evaluation vocabulary: causation vs correlation, p-hacking, confirmation bias, statistical rigor.",
  },
  {
    id: "C1.2-M10",
    levelId: "C1.2",
    title: "Advanced Narrative Arc: Retrospective Realism & Dual-Timeline Tenses",
    group: "C1.2 - Strategic Oratory & Complex Syntax",
    objective: "Menggabungkan past perfect continuous, unfulfilled past intentions, dan modal perfects untuk menyusun narasi mendalam.",
    orderIndex: 10,
    isExam: false,
    passingScore: 70,
    promptNotes: "Dual temporal frames, retrospective introspection, literary past tenses, psychological pacing.",
  },
  {
    id: "C1.2-M11",
    levelId: "C1.2",
    title: "Epistemic Stance & Critical Discourse Analysis of Editorial Journalism",
    group: "C1.2 - Strategic Oratory & Complex Syntax",
    objective: "Membongkar ideologi tersembunyi, konotasi leksikal, dan framing media dalam tajuk rencana surat kabar internasional.",
    orderIndex: 11,
    isExam: false,
    passingScore: 70,
    promptNotes: "Critical discourse analysis (CDA), presupposition, ideological framing, editorial slant.",
  },
  {
    id: "C1.2-M12",
    levelId: "C1.2",
    title: "Public Oratory & Keynote Presentation Techniques: Triads & Parallelism",
    group: "C1.2 - Strategic Oratory & Complex Syntax",
    objective: "Menguasai perangkat retorika publik (tricolon/rule of three, parallel structure, hypophora) untuk presentasi berbobot.",
    orderIndex: 12,
    isExam: false,
    passingScore: 70,
    promptNotes: "Classical oratorical figures, tricolon, antithetical parallelism, dynamic voice projection and emphasis.",
  },
  {
    id: "C1.2-M13",
    levelId: "C1.2",
    title: "Ujian Kelulusan C1.2: Evaluasi Komprehensif Strategic Oratory & Complex Syntax",
    group: "C1.2 - Strategic Oratory & Complex Syntax",
    objective: "Ujian kelulusan komprehensif 4 keterampilan (Listening, Reading, Writing, Speaking) untuk membuka Sub-Level C1.3",
    orderIndex: 13,
    isExam: true,
    passingScore: 75,
    promptNotes: "Ujian 16 butir soal (4 Listening debat akademis, 4 Reading analisis kritis, 4 Writing nominalisasi/sintaksis, 4 Speaking oratori persuasif).",
  },
];

export const C1_3_SYLLABUS: ModuleMeta[] = [
  {
    id: "C1.3-M01",
    levelId: "C1.3",
    title: "High-Level Idiomatic Collocations & Phrasal Verb Nuance in Executive Settings",
    group: "C1.3 - Critical Dialectics & Bridge to C2",
    objective: "Menguasai kolokasi idiomatis tingkat tinggi (cut corners, throw down the gauntlet, toe the line) dan phrasal verbs berkonotasi abstrak.",
    orderIndex: 1,
    isExam: false,
    passingScore: 70,
    promptNotes: "Abstract phrasal verbs: flesh out, zero in on, pare down, paper over. Executive idiomatic precision.",
  },
  {
    id: "C1.3-M02",
    levelId: "C1.3",
    title: "Stylistic Inversion After Limiting & Negative Adverbial Expressions",
    group: "C1.3 - Critical Dialectics & Bridge to C2",
    objective: "Menerapkan struktur inversi tingkat mahir (In no way, Under no circumstances, On no account, Scarcely... when).",
    orderIndex: 2,
    isExam: false,
    passingScore: 70,
    promptNotes: "Limiting adverbial inversion, formal prohibition syntax, high stylistic polish.",
  },
  {
    id: "C1.3-M03",
    levelId: "C1.3",
    title: "Stylistic Cleft Structures: Wh-clefts, Reverse Clefts & All-clefts",
    group: "C1.3 - Critical Dialectics & Bridge to C2",
    objective: "Menguasai variasi kalimat terbelah (cleft sentences) untuk mengatur puncak informasi (focus) dan kontras tegas dalam argumen.",
    orderIndex: 3,
    isExam: false,
    passingScore: 70,
    promptNotes: "Wh-clefts with emotive verbs, reversed pseudo-clefts, all-clefts for emphatic exclusivity.",
  },
  {
    id: "C1.3-M04",
    levelId: "C1.3",
    title: "Geopolitical Analysis, International Treaties & Diplomatic Protocol",
    group: "C1.3 - Critical Dialectics & Bridge to C2",
    objective: "Menganalisis pakta keamanan multilateral, kedaulatan maritim, sanksi ekonomi, dan protokol diplomatik PBB.",
    orderIndex: 4,
    isExam: false,
    passingScore: 70,
    promptNotes: "Geopolitical lexicon: sovereignty, non-proliferation, multilateral accord, ratified stipulations.",
  },
  {
    id: "C1.3-M05",
    levelId: "C1.3",
    title: "Philosophical Debate: Utilitarianism, Deontology & Ethical Dilemmas",
    group: "C1.3 - Critical Dialectics & Bridge to C2",
    objective: "Memperdebatkan etika moral, paradoks utilitarian vs deontologis, dan dilema moral dalam kecerdasan buatan.",
    orderIndex: 5,
    isExam: false,
    passingScore: 70,
    promptNotes: "Ethical philosophy vocabulary: categorical imperative, consequentialism, moral hazard, triage ethics.",
  },
  {
    id: "C1.3-M06",
    levelId: "C1.3",
    title: "Literary Appreciation: Sensory Imagery, Extended Metaphors & Allegory",
    group: "C1.3 - Critical Dialectics & Bridge to C2",
    objective: "Membedah karya sastra klasik dan modern melalui analisis majas metafora berantai, simbolisme, dan alegori.",
    orderIndex: 6,
    isExam: false,
    passingScore: 70,
    promptNotes: "Literary analysis devices: conceit, motif, synesthesia, allegorical subtext, evocative imagery.",
  },
  {
    id: "C1.3-M07",
    levelId: "C1.3",
    title: "Advanced Spoken Nuance: Intonation Shifts, Irony Detection & Sarcasm Cues",
    group: "C1.3 - Critical Dialectics & Bridge to C2",
    objective: "Mendeteksi sarkasme halus, understatements khas British English, dan perubahan kontur intonasi dalam interaksi sosial.",
    orderIndex: 7,
    isExam: false,
    passingScore: 70,
    promptNotes: "Acoustic prosody cues, deadpan irony, English litotes (not unpleasing, rather unfortunate), pragmatic competence.",
  },
  {
    id: "C1.3-M08",
    levelId: "C1.3",
    title: "Academic Peer Review & Defending Original Scientific Theses",
    group: "C1.3 - Critical Dialectics & Bridge to C2",
    objective: "Menyusun tanggapan kritis terhadap laporan peer-review dan mempertahankan integritas metodologi di hadapan dewan penguji.",
    orderIndex: 8,
    isExam: false,
    passingScore: 70,
    promptNotes: "Peer-review rebuttals, scholastic defense, acknowledging limitations constructively, collegial refutation.",
  },
  {
    id: "C1.3-M09",
    levelId: "C1.3",
    title: "Environmental Geopolitics & Climate Policy Discourse",
    group: "C1.3 - Critical Dialectics & Bridge to C2",
    objective: "Mendiskusikan transisi energi hijau, skema kredit karbon, geoengineering, dan keadilan iklim global.",
    orderIndex: 9,
    isExam: false,
    passingScore: 70,
    promptNotes: "Environmental terminology: decarbonisation, ecological footprint, carbon offsets, tipping points.",
  },
  {
    id: "C1.3-M10",
    levelId: "C1.3",
    title: "High-Stakes Crisis Communication & Executive Press Briefings",
    group: "C1.3 - Critical Dialectics & Bridge to C2",
    objective: "Menghadapi pertanyaan tajam jurnalis investigatif saat konferensi pers krisis korporasi atau kegagalan sistem.",
    orderIndex: 10,
    isExam: false,
    passingScore: 70,
    promptNotes: "Crisis management oratory, bridging techniques (pivot words), defusing loaded questions under pressure.",
  },
  {
    id: "C1.3-M11",
    levelId: "C1.3",
    title: "Behavioral Economics, Heuristics & Cognitive Biases in Decision Making",
    group: "C1.3 - Critical Dialectics & Bridge to C2",
    objective: "Menganalisis psikologi pengambilan keputusan ekonomi: loss aversion, framing effect, hyperbolic discounting.",
    orderIndex: 11,
    isExam: false,
    passingScore: 70,
    promptNotes: "Behavioral economics lexicon: nudging, bounded rationality, prospect theory, sunk cost fallacy.",
  },
  {
    id: "C1.3-M12",
    levelId: "C1.3",
    title: "Bridge to C2: Synthesising Multiple Opposing Sources into Unified Arguments",
    group: "C1.3 - Critical Dialectics & Bridge to C2",
    objective: "Mengintegrasikan 3-4 artikel bertentangan menjadi satu sintesis kritis orisinal dengan gaya bahasa elegan siap menuju level C2.",
    orderIndex: 12,
    isExam: false,
    passingScore: 70,
    promptNotes: "Multi-source synthesis, harmonising conflicting empirical findings, thesis elevation, springboard to C2 mastery.",
  },
  {
    id: "C1.3-M13",
    levelId: "C1.3",
    title: "Ujian Kelulusan C1.3: Evaluasi Komprehensif Critical Dialectics & Bridge to C2",
    group: "C1.3 - Critical Dialectics & Bridge to C2",
    objective: "Ujian kelulusan akhir Level C1 (16 butir soal komprehensif 4 keterampilan) untuk membuka Level C2 (Mastery).",
    orderIndex: 13,
    isExam: true,
    passingScore: 75,
    promptNotes: "Ujian kelulusan akhir C1: 16 butir soal (4 Listening pidato diplomatik, 4 Reading jurnal filsafat, 4 Writing sintesis dialektis, 4 Speaking debat krisis).",
  },
];
