export interface ModuleMeta {
  id: string;
  levelId: string;
  title: string;
  group: string;
  objective: string;
  orderIndex: number;
  isExam: boolean;
  passingScore: number;
  promptNotes: string;
}

export const C2_1_EXAM_META: ModuleMeta = {
  id: "C2.1-M13",
  levelId: "C2.1",
  title: "Ujian Kelulusan C2.1: Evaluasi Komprehensif Mastery Foundations & Rhetoric",
  group: "C2.1 - Mastery Foundations & Rhetorical Wit",
  objective:
    "Ujian kelulusan komprehensif 4 keterampilan (Listening, Reading, Writing, Speaking) untuk membuka Sub-Level C2.2",
  orderIndex: 13,
  isExam: true,
  passingScore: 75,
  promptNotes:
    "Ujian komprehensif 4-Skills C2.1: 16 butir soal (4 Listening monolog saintifik/filsafat, 4 Reading esai sastra/hukum, 4 Writing retorika kompleks, 4 Speaking oratori persuasif). Topik: habitual nuances, narrative psychology, advanced conditionals, clefts, inversion, relative structures.",
};

export const C2_2_SYLLABUS: ModuleMeta[] = [
  {
    id: "C2.2-M01",
    levelId: "C2.2",
    title: "Nuanced Satire, Irony & High-Level Rhetorical Sarcasm in Cultural Commentary",
    group: "C2.2 - Dialectical Precision & Semiotic Depth",
    objective: "Menganalisis dan menyusun kritik sosial bernada satir, sarkasme terselubung, parodi sastra, dan humor intelektual.",
    orderIndex: 1,
    isExam: false,
    passingScore: 70,
    promptNotes: "Satirical devices, Swiftian irony, parody, lampoon, deadpan commentary, cultural subversion.",
  },
  {
    id: "C2.2-M02",
    levelId: "C2.2",
    title: "Semiotics, Cultural Linguistics & Linguistic Relativity",
    group: "C2.2 - Dialectical Precision & Semiotic Depth",
    objective: "Mengeksplorasi hubungan antara struktur bahasa, persepsi kognitif dunia (hipotesis Sapir-Whorf), dan semiotika tanda.",
    orderIndex: 2,
    isExam: false,
    passingScore: 70,
    promptNotes: "Semiotic terminology: signifier, signified, linguistic determinism, cultural encoding, untranslatability.",
  },
  {
    id: "C2.2-M03",
    levelId: "C2.2",
    title: "Supreme Court & Constitutional Jurisprudence Discourse",
    group: "C2.2 - Dialectical Precision & Semiotic Depth",
    objective: "Mendiskusikan penafsiran undang-undang, preseden peradilan (stare decisis), dissenting opinions hakim agung, dan doktrin konstitusional.",
    orderIndex: 3,
    isExam: false,
    passingScore: 70,
    promptNotes: "Legal philosophy & jurisprudence: originalism vs living constitution, statutory ambiguity, judicial review.",
  },
  {
    id: "C2.2-M04",
    levelId: "C2.2",
    title: "Masterful Epistemic & Deontic Modality in Philosophical Argumentation",
    group: "C2.2 - Dialectical Precision & Semiotic Depth",
    objective: "Menggunakan gradasi modalitas epistemik dan deontik tingkat tertinggi untuk membedah argumen ontologis dan epistemologis.",
    orderIndex: 4,
    isExam: false,
    passingScore: 70,
    promptNotes: "Modal nuances: necessity vs contingency, a priori vs a posteriori deduction, modal logic discourse.",
  },
  {
    id: "C2.2-M05",
    levelId: "C2.2",
    title: "Classical Rhetoric: Chiasmus, Zeugma, Polysyndeton & Asyndeton in Modern Prose",
    group: "C2.2 - Dialectical Precision & Semiotic Depth",
    objective: "Menerapkan majas retorika klasik Yunani-Romawi untuk menciptakan prosa bahasa Inggris yang memiliki musikalitas tinggi.",
    orderIndex: 5,
    isExam: false,
    passingScore: 70,
    promptNotes: "Classical rhetorical tropes: chiasmus (Ask not...), zeugma, polysyndeton, asyndeton, rhythmic cadence.",
  },
  {
    id: "C2.2-M06",
    levelId: "C2.2",
    title: "Complex Metaphorical Mapping in Literature, Poetry & Avant-Garde Prose",
    group: "C2.2 - Dialectical Precision & Semiotic Depth",
    objective: "Menganalisis sistem konseptual metafora (Lakoff & Johnson) dalam karya sastra modernis dan puisi eksperimental.",
    orderIndex: 6,
    isExam: false,
    passingScore: 70,
    promptNotes: "Conceptual metaphor theory, target and source domains, poetic defamiliarisation, stream of imagery.",
  },
  {
    id: "C2.2-M07",
    levelId: "C2.2",
    title: "High-Finance Mergers, Derivative Markets & Sovereign Debt Restructuring",
    group: "C2.2 - Dialectical Precision & Semiotic Depth",
    objective: "Menguasai diskursus perbankan investasi internasional: derivatif terstruktur, restrukturisasi utang negara, dan arbitrase kuantitatif.",
    orderIndex: 7,
    isExam: false,
    passingScore: 70,
    promptNotes: "Wall Street & City of London jargon: leveraged buyout, credit default swap, liquidity crunch, fiscal austerity.",
  },
  {
    id: "C2.2-M08",
    levelId: "C2.2",
    title: "Dialectical Synthesis: Resolving Hegelian Contradictions in Public Policy",
    group: "C2.2 - Dialectical Precision & Semiotic Depth",
    objective: "Menyusun argumen dialektis (Tesis, Antitesis, Sintesis) untuk memecahkan dilema regulasi teknologi dan kebebasan sipil.",
    orderIndex: 8,
    isExam: false,
    passingScore: 70,
    promptNotes: "Dialectical argumentation, synthesis of opposing societal values, structural reconciliation, policy debate.",
  },
  {
    id: "C2.2-M09",
    levelId: "C2.2",
    title: "Psycholinguistics, Cognitive Neuroscience & The Mechanics of Fluent Thought",
    group: "C2.2 - Dialectical Precision & Semiotic Depth",
    objective: "Mendiskusikan pemrosesan bahasa di otak, afasia, neurolinguistik, dan fenomena 'tip-of-the-tongue'.",
    orderIndex: 9,
    isExam: false,
    passingScore: 70,
    promptNotes: "Cognitive science lexicon: neural plasticity, lexical retrieval, Broca's area, linguistic modularity.",
  },
  {
    id: "C2.2-M10",
    levelId: "C2.2",
    title: "Diplomatic Brinkmanship, Summit Communiqués & Multilateral Negotiation",
    group: "C2.2 - Dialectical Precision & Semiotic Depth",
    objective: "Menafsirkan teks komunike bersama KTT antar-negara, manuver diplomatik berisiko tinggi (brinkmanship), dan klausul ambiguitas konstruktif.",
    orderIndex: 10,
    isExam: false,
    passingScore: 70,
    promptNotes: "Diplomatic lexicon: constructive ambiguity, détente, communique drafting, diplomatic demarche.",
  },
  {
    id: "C2.2-M11",
    levelId: "C2.2",
    title: "Postmodern Literary Criticism & Deconstructionist Discourse",
    group: "C2.2 - Dialectical Precision & Semiotic Depth",
    objective: "Membedah teks sastra menggunakan paradigma post-strukturalisme (Derrida, Foucault): intertekstualitas, dekonstruksi, dan kuasa diskursus.",
    orderIndex: 11,
    isExam: false,
    passingScore: 70,
    promptNotes: "Literary theory lexicon: intertextuality, logocentrism, discourse power, simulacra, binary oppositions.",
  },
  {
    id: "C2.2-M12",
    levelId: "C2.2",
    title: "Ethical Implications of Artificial Superintelligence, Transhumanism & Consciousness",
    group: "C2.2 - Dialectical Precision & Semiotic Depth",
    objective: "Memperdebatkan masa depan umat manusia: penyelarasan kecerdasan buatan (alignment problem), singularitas teknologi, dan hak eksistensial cyborg.",
    orderIndex: 12,
    isExam: false,
    passingScore: 70,
    promptNotes: "AI existential risk: alignment problem, sentient algorithms, transhumanism, qualia of consciousness.",
  },
  {
    id: "C2.2-M13",
    levelId: "C2.2",
    title: "Ujian Kelulusan C2.2: Evaluasi Komprehensif Dialectical Precision & Semiotic Depth",
    group: "C2.2 - Dialectical Precision & Semiotic Depth",
    objective: "Ujian kelulusan komprehensif 4 keterampilan (Listening, Reading, Writing, Speaking) untuk membuka Sub-Level C2.3 (Grandmastery).",
    orderIndex: 13,
    isExam: true,
    passingScore: 75,
    promptNotes: "Ujian 16 butir soal (4 Listening kuliah filsafat Oxford, 4 Reading putusan Mahkamah Agung, 4 Writing dekonstruksi teks, 4 Speaking debat etika AI).",
  },
];

export const C2_3_SYLLABUS: ModuleMeta[] = [
  {
    id: "C2.3-M01",
    levelId: "C2.3",
    title: "Archaisms, Neologisms & The Evolution of English Lexicon Across Millennia",
    group: "C2.3 - Ultimate Native Fluency & Grandmastery",
    objective: "Menelusuri etimologi kata, pergeseran semantik historis (pejoration, amelioration), dan integrasi neologisme digital terkini.",
    orderIndex: 1,
    isExam: false,
    passingScore: 70,
    promptNotes: "Historical linguistics: semantic drift, archaic vocabulary, loanwords, morphological innovation.",
  },
  {
    id: "C2.3-M02",
    levelId: "C2.3",
    title: "Masterclass in Epigrammatic Wit & Aphoristic Prose",
    group: "C2.3 - Ultimate Native Fluency & Grandmastery",
    objective: "Menulis aforisme tajam dan kalimat epigramatik yang memadukan keindahan bahasa, kejutan logika, dan kedalaman makna filosofis.",
    orderIndex: 2,
    isExam: false,
    passingScore: 70,
    promptNotes: "Epigrams, aphoristic brevity, paradox, Oscar Wildean wit, pungent observations on human nature.",
  },
  {
    id: "C2.3-M03",
    levelId: "C2.3",
    title: "In-Depth Hermeneutics: Reading Between the Lines in Historic Political Treatises",
    group: "C2.3 - Ultimate Native Fluency & Grandmastery",
    objective: "Menafsirkan makna tersirat dalam risalah politik klasik (The Prince karya Machiavelli, Leviathan karya Hobbes, Federalist Papers).",
    orderIndex: 3,
    isExam: false,
    passingScore: 70,
    promptNotes: "Hermeneutic analysis: authorial intentionality, contextual subtext, political statecraft rhetoric.",
  },
  {
    id: "C2.3-M04",
    levelId: "C2.3",
    title: "The Art of Subtle Persuasion: Covert Rhetoric & Soft Power Diplomacy",
    group: "C2.3 - Ultimate Native Fluency & Grandmastery",
    objective: "Menerapkan persuasi halus tanpa kesan memaksa: framing subliminal, pra-suposisi leksikal, dan diplomasi kebudayaan global.",
    orderIndex: 4,
    isExam: false,
    passingScore: 70,
    promptNotes: "Covert persuasion, soft power dynamics, strategic ambiguity, unspoken consensus engineering.",
  },
  {
    id: "C2.3-M05",
    levelId: "C2.3",
    title: "Dialectology, Sociolects & Register-Shifting in World Englishes",
    group: "C2.3 - Ultimate Native Fluency & Grandmastery",
    objective: "Mengapresiasi keragaman World Englishes (RP, General American, Hiberno-English, Singlish, Australian) dan pergeseran kode sosial.",
    orderIndex: 5,
    isExam: false,
    passingScore: 70,
    promptNotes: "Sociolinguistics: code-switching, prestige dialects, phonetic variations, global pluricentric English.",
  },
  {
    id: "C2.3-M06",
    levelId: "C2.3",
    title: "High Academic Monograph Writing: Defending Original Conceptual Paradigms",
    group: "C2.3 - Ultimate Native Fluency & Grandmastery",
    objective: "Menulis bab pendahuluan monograf doktoral yang memperkenalkan kerangka teoritis baru dan membantah ortodoksi akademik lama.",
    orderIndex: 6,
    isExam: false,
    passingScore: 70,
    promptNotes: "Doctoral-level prose: paradigm shifts, epistemic breakthrough, theoretical justification, rigorous scholarly apparatus.",
  },
  {
    id: "C2.3-M07",
    levelId: "C2.3",
    title: "Subversive Narratives, Unreliable Narrators & Stream of Consciousness",
    group: "C2.3 - Ultimate Native Fluency & Grandmastery",
    objective: "Menganalisis teknik naratif modernis ala James Joyce dan Virginia Woolf: stream of consciousness, narator tak andal, dan non-linearitas waktu.",
    orderIndex: 7,
    isExam: false,
    passingScore: 70,
    promptNotes: "Narratology: unreliable narrator, interior monologue, temporal distortion, modernist prose craft.",
  },
  {
    id: "C2.3-M08",
    levelId: "C2.3",
    title: "Crisis Negotiations: High-Stakes Hostage & Geopolitical De-escalation Scripts",
    group: "C2.3 - Ultimate Native Fluency & Grandmastery",
    objective: "Menerapkan psikolinguistik de-eskalasi dalam situasi krisis ekstrem: active listening labels, calibrated questions, dan mirroring.",
    orderIndex: 8,
    isExam: false,
    passingScore: 70,
    promptNotes: "Hostage negotiation linguistics: tactical empathy, calibrated questions, emotional labeling, de-escalation cadence.",
  },
  {
    id: "C2.3-M09",
    levelId: "C2.3",
    title: "Philosophy of Mind, Epistemology & Radical Skepticism in Modern Science",
    group: "C2.3 - Ultimate Native Fluency & Grandmastery",
    objective: "Mendiskusikan argumen simulasi (Nick Bostrom), solipsisme, batas-batas empirisme, dan hakikat realitas fisik.",
    orderIndex: 9,
    isExam: false,
    passingScore: 70,
    promptNotes: "Epistemological discourse: radical skepticism, simulation hypothesis, foundationalism, hard problem of consciousness.",
  },
  {
    id: "C2.3-M10",
    levelId: "C2.3",
    title: "Forensic Linguistic Analysis: Authorship Identification & Semantic Disambiguation",
    group: "C2.3 - Ultimate Native Fluency & Grandmastery",
    objective: "Menganalisis teks forensik pengadilan: idiolek penulis, analisis korpus stylometrik, dan pengungkapan ancaman terselubung.",
    orderIndex: 10,
    isExam: false,
    passingScore: 70,
    promptNotes: "Forensic linguistics: stylometry, idiolect identification, syntactic markers in threat analysis.",
  },
  {
    id: "C2.3-M11",
    levelId: "C2.3",
    title: "Grandmaster Debate: Spontaneous Refutation of Sophistical Fallacies in Real-Time",
    group: "C2.3 - Ultimate Native Fluency & Grandmastery",
    objective: "Menangkis falasi canggih lawan debat (tu quoque, motte-and-bailey, red herring, begging the question) secara spontan dan elegan.",
    orderIndex: 11,
    isExam: false,
    passingScore: 70,
    promptNotes: "Parliamentary debating oratory: dissecting informal fallacies, instantaneous rebuttal, rhetorical elegance under pressure.",
  },
  {
    id: "C2.3-M12",
    levelId: "C2.3",
    title: "Capstone Synthesis: The Sovereign English Speaker — Effortless Fluency & Artistry",
    group: "C2.3 - Ultimate Native Fluency & Grandmastery",
    objective: "Mencapai kefasihan berdaulat (sovereign fluency): kebebasan memilih ragam bahasa apapun secara instan dengan ketepatan makna mutlak.",
    orderIndex: 12,
    isExam: false,
    passingScore: 70,
    promptNotes: "Sovereign English mastery: aesthetic command of prose, instinctive pragmatic precision, native-transcending fluency.",
  },
  {
    id: "C2.3-M13",
    levelId: "C2.3",
    title: "Ujian Kelulusan C2.3: Grandmastery Proficiency Examination (C2 Complete)",
    group: "C2.3 - Ultimate Native Fluency & Grandmastery",
    objective: "Ujian penutup seluruh kurikulum Eddys AI (Level C2 Grandmastery) — 16 butir soal komprehensif 4 keterampilan setara Cambridge CPE.",
    orderIndex: 13,
    isExam: true,
    passingScore: 75,
    promptNotes: "Ujian akhir kurikulum bahasa Inggris (CPE Level): 16 butir soal (4 Listening monolog intelektual, 4 Reading analisis hermeneutik, 4 Writing esai filosofis orisinal, 4 Speaking oratori dan debat puncak).",
  },
];
